#!/bin/sh
# -*- encoding: utf-8; indent-tabs-mode: nil -*-
#
#     Programme pour lancer une partie de l'As des As
#     Program to launch an Ace of Aces game
#     Copyright (C) 2018 Jean Forget
#    
#    Ce programme est diffusé avec les mêmes conditions que Perl 5.16.3 :
#    la licence publique GPL version 1 ou ultérieure, ou bien la
#    licence artistique Perl.
#    
#    Vous pouvez trouver le texte en anglais de ces licences dans le
#    fichier <LICENSE> joint ou bien aux adresses
#    L<http://www.perlfoundation.org/artistic_license_1_0>
#    et L<http://www.gnu.org/licenses/gpl-1.0.html>.
#    
#    Résumé en anglais de la GPL :
#    
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 1, or (at your option)
#    any later version.
#    
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#    
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software Foundation,
#    Inc., L<http://www.fsf.org/>.

export dh=$(date +'%Y-%m-%d_%H-%M-%S')

perl6 arbitre.p6 --date-heure=$dh --gentil=Epervier --méchant=Drone --à-outrance &
perl6 joueur.p6  --date-heure=$dh --identité=Drone    &
perl6 joueur.p6  --date-heure=$dh --identité=Epervier &

#perl6 arbitre.p6 --date-heure=$dh --gentil=Plume-Noire --mechant=Kevin &
#perl6 joueur.p6  --date-heure=$dh --identité=Kevin
#perl6 joueur.p6  --date-heure=$dh --identité=Plume-Noire
