-*- encoding: utf-8; indent-tabs-mode: nil -*-

=encoding utf-8

=head1 Explication / Explanation

Le programme C<aff.p6> génère un fichier HTML. Le problème est que Github affiche les fichiers HTML en
tant que fichiers sources et non pas en tant que documents mis en forme. J'ai donc converti ce fichier
en fichier POD pour que Github l'affiche correctement. Il y a des problèmes néanmoins avec les styles
permettant théoriquement d'afficher du texte sur un fond coloré. Vous pouvez toujours télécharger le fichier
HTML sur votre poste et l'afficher dans votre navigateur web.

The C<aff.p6> program generates an HTML file. The problem is that Github displays HTML files as
source files, not as real documents. I have converted this HTML file into POD, so Github will
render it correctly. There is still a problem with the stylesheet which, in this case, should
change the background color for some texts. You can still download the HTML file and display it
with your favorite web browser.

Le tableau et le schéma ci-dessous sont obtenus après l'enchaînement suivant / the table and
the picture below are built with:

  perl6 init.p6
  perl6 maj.p6 --page=187 -a=205 -b=187 -c=198 -d=3   -e=15  -f=16  -g=2   -h=17  -i=1
  perl6 aff.p6 > etape1.html

Ce que vous ne voyez pas ci-dessous : dans le tableau, la ligne 187 est entièrement en vert,
car les valeurs proviennent toutes des paramètres de la ligne de commande. Les cases avec des
points d'interrogation sont en rose pour indiquer, comme vous vous en doutez, que la transition
correspondante n'est pas connue. En dehors de la ligne 187, les cases avec un numéro sont en
jaune pour indiquer qu'elles ont été calculées au lieu d'être directement saisies en ligne de
commande. Dans le schéma, les numéros de page sont également imprimés sur fond S<coloré :> en
rose s'il y a au moins une transition en rose dans le tableau, en jaune s'il y a au moins une
transtion en jaune dans le tableau et qu'il n'y a aucune transition en rose (aucun cas dans cet
exemple) et finalement en vert si toutes les transitions sont en vert.

What you do not see below: in the table, line 187 is fully green, because all transitions
have been entered from the command line. Transitions with question marks are in pink because,
as you guessed it, they are yet unknown. Transitions in yellow are transitions which were
computed by the F<maj.p6> program, without being entered as command parameters. In the picture
below, the page numbers are also printed on a color background: pink if this page includes
at least one pink unknown transition, yellow if the page has no unknown transition but at least
one computed transition and green if all transitions for the page number are green.

Les colonnes 2 et 3, avec des points-virgules, correspondent à l'implémentation interne
de la classe F<Depl.pm6> utilisée par les programmes de préparation.

Columns 2 and 3, with semi-colons, display part of the internal implementation of
class F<Depl.pm6>, used by the preparation programs.

=begin html

<table border='1'>
<tr><td>1</td><td>2;0</td><td>5;0</td><td style='background-color: pink'>A  ?? </td><td style='background-color: yellow'>B  1 </td><td style='background-color: pink'>C  ?? </td><td style='background-color: yellow'>D  2 </td><td style='background-color: yellow'>E  187 </td><td style='background-color: yellow'>F  17 </td><td style='background-color: pink'>G  ?? </td><td style='background-color: pink'>H  ?? </td><td style='background-color: pink'>I  ?? </td></tr>
<tr><td>2</td><td>3;0</td><td>0;0</td><td style='background-color: pink'>A  ?? </td><td style='background-color: yellow'>B  2 </td><td style='background-color: pink'>C  ?? </td><td style='background-color: pink'>D  ?? </td><td style='background-color: yellow'>E  3 </td><td style='background-color: yellow'>F  187 </td><td style='background-color: pink'>G  ?? </td><td style='background-color: yellow'>H  1 </td><td style='background-color: pink'>I  ?? </td></tr>
<tr><td>3</td><td>4;0</td><td>1;0</td><td style='background-color: pink'>A  ?? </td><td style='background-color: yellow'>B  3 </td><td style='background-color: pink'>C  ?? </td><td style='background-color: pink'>D  ?? </td><td style='background-color: pink'>E  ?? </td><td style='background-color: yellow'>F  15 </td><td style='background-color: pink'>G  ?? </td><td style='background-color: yellow'>H  187 </td><td style='background-color: yellow'>I  2 </td></tr>
<tr><td>15</td><td>5;0</td><td>2;0</td><td style='background-color: pink'>A  ?? </td><td style='background-color: yellow'>B  15 </td><td style='background-color: pink'>C  ?? </td><td style='background-color: pink'>D  ?? </td><td style='background-color: pink'>E  ?? </td><td style='background-color: pink'>F  ?? </td><td style='background-color: yellow'>G  3 </td><td style='background-color: yellow'>H  16 </td><td style='background-color: yellow'>I  187 </td></tr>
<tr><td>16</td><td>0;0</td><td>3;0</td><td style='background-color: pink'>A  ?? </td><td style='background-color: yellow'>B  16 </td><td style='background-color: pink'>C  ?? </td><td style='background-color: yellow'>D  15 </td><td style='background-color: pink'>E  ?? </td><td style='background-color: pink'>F  ?? </td><td style='background-color: yellow'>G  187 </td><td style='background-color: pink'>H  ?? </td><td style='background-color: yellow'>I  17 </td></tr>
<tr><td>17</td><td>1;0</td><td>4;0</td><td style='background-color: pink'>A  ?? </td><td style='background-color: yellow'>B  17 </td><td style='background-color: pink'>C  ?? </td><td style='background-color: yellow'>D  187 </td><td style='background-color: yellow'>E  16 </td><td style='background-color: pink'>F  ?? </td><td style='background-color: yellow'>G  1 </td><td style='background-color: pink'>H  ?? </td><td style='background-color: pink'>I  ?? </td></tr>
<tr><td>187</td><td>;0</td><td>;0</td><td style='background-color: lightgreen'>A  205 </td><td style='background-color: lightgreen'>B  187 </td><td style='background-color: lightgreen'>C  198 </td><td style='background-color: lightgreen'>D  3 </td><td style='background-color: lightgreen'>E  15 </td><td style='background-color: lightgreen'>F  16 </td><td style='background-color: lightgreen'>G  2 </td><td style='background-color: lightgreen'>H  17 </td><td style='background-color: lightgreen'>I  1 </td></tr>
<tr><td>198</td><td>;1</td><td>;5</td><td style='background-color: yellow'>A  187 </td><td style='background-color: yellow'>B  198 </td><td style='background-color: pink'>C  ?? </td><td style='background-color: pink'>D  ?? </td><td style='background-color: pink'>E  ?? </td><td style='background-color: pink'>F  ?? </td><td style='background-color: pink'>G  ?? </td><td style='background-color: pink'>H  ?? </td><td style='background-color: pink'>I  ?? </td></tr>
<tr><td>205</td><td>;5</td><td>;1</td><td style='background-color: pink'>A  ?? </td><td style='background-color: yellow'>B  205 </td><td style='background-color: yellow'>C  187 </td><td style='background-color: pink'>D  ?? </td><td style='background-color: pink'>E  ?? </td><td style='background-color: pink'>F  ?? </td><td style='background-color: pink'>G  ?? </td><td style='background-color: pink'>H  ?? </td><td style='background-color: pink'>I  ?? </td></tr>
<tr><td>223</td></tr>
</table>
<pre>
.                                -------
.                               /       \
.                              /         \
.                       -------           -------
.                      /       \         /       \
.                     /         \       /         \
.              -------           -------           -------
.             /       \         /       \         /       \
.            /         \       /         \       /         \
.     -------           -------           -------           -------
.    /       \         /       \         /       \         /       \
.   /         \       /         \       /         \       /         \
.  (           -------           -------           -------           )
.   \         /       \         /  <span style='background-color: pink'> 16</span>  \         /       \         /
.    \       /         \       /         \       /         \       /
.     -------           -------           -------           -------
.    /       \         /  <span style='background-color: pink'> 15</span>  \         /  <span style='background-color: pink'> 17</span>  \         /       \
.   /         \       /         \       /         \       /         \
.  (           -------           -------           -------           )
.   \         /       \         /  <span style='background-color: lightgreen'>187</span>  \         /       \         /
.    \       /         \       /<span style='background-color: pink'>205</span>   <span style='background-color: pink'>198</span>\       /         \       /
.     -------           -------           -------           -------
.    /       \         /  <span style='background-color: pink'> 3 </span>  \         /  <span style='background-color: pink'> 1 </span>  \         /       \
.   /         \       /         \       /         \       /         \
.  (           -------           -------           -------           )
.   \         /       \         /  <span style='background-color: pink'> 2 </span>  \         /       \         /
.    \       /         \       /         \       /         \       /
.     -------           -------           -------           -------
.    /       \         /       \         /       \         /       \
.   /         \       /         \       /         \       /         \
.  (           -------           -------           -------           )
.   \         /       \         /       \         /       \         /
.    \       /         \       /         \       /         \       /
.     -------           -------           -------           -------
.            \         /       \         /       \         /
.             \       /         \       /         \       /
.              -------           -------           -------
.                     \         /       \         /
.                      \       /         \       /
.                       -------           -------
.                              \         /
.                               \       /
.                                -------

</pre>

=end html

=head1 LICENCE / LICENSE

Texte diffusé sous la licence CC-BY-NC-ND : Creative Commons avec clause de paternité, excluant l'utilisation commerciale et excluant la modification. 

This text is published under the CC-BY-NC-ND license: Attribution-NonCommercial-NoDerivs 2.0 Generic.
