-*- encoding: utf-8; indent-tabs-mode: nil -*-

=encoding utf-8

=head1 Explication / Explanation

Le programme C<aff.p6> génère un fichier HTML. Le problème est que Github affiche les fichiers HTML en
tant que fichiers sources et non pas en tant que documents mis en forme. J'ai donc converti ce fichier
en fichier POD pour que Github l'affiche correctement. Il y a des problèmes néanmoins avec les styles
permettant théoriquement d'afficher du texte sur un fond coloré. Vous pouvez toujours télécharger le fichier
HTML sur votre poste et l'afficher dans votre navigateur web.

The C<aff.p6> program generates an HTML file. The problem is that Github displays HTML files as
source files, not as real documents. I have converted this HTML file into POD, so Github will
render it correctly. There is still a problem with the stylesheet which, in this case, should
change the background color for some texts. You can still download the HTML file and display it
with your favorite web browser.

=begin html

<table border='1'>
<tr><td>1</td><td>2;0</td><td>5;0</td><td style='background-color: pink'>A  ?? </td><td style='background-color: yellow'>B  1 </td><td style='background-color: pink'>C  ?? </td><td style='background-color: yellow'>D  2 </td><td style='background-color: yellow'>E  187 </td><td style='background-color: yellow'>F  17 </td><td style='background-color: pink'>G  ?? </td><td style='background-color: pink'>H  ?? </td><td style='background-color: pink'>I  ?? </td></tr>
<tr><td>2</td><td>3;0</td><td>0;0</td><td style='background-color: pink'>A  ?? </td><td style='background-color: yellow'>B  2 </td><td style='background-color: pink'>C  ?? </td><td style='background-color: pink'>D  ?? </td><td style='background-color: yellow'>E  3 </td><td style='background-color: yellow'>F  187 </td><td style='background-color: pink'>G  ?? </td><td style='background-color: yellow'>H  1 </td><td style='background-color: pink'>I  ?? </td></tr>
<tr><td>3</td><td>4;0</td><td>1;0</td><td style='background-color: pink'>A  ?? </td><td style='background-color: yellow'>B  3 </td><td style='background-color: pink'>C  ?? </td><td style='background-color: pink'>D  ?? </td><td style='background-color: pink'>E  ?? </td><td style='background-color: yellow'>F  15 </td><td style='background-color: pink'>G  ?? </td><td style='background-color: yellow'>H  187 </td><td style='background-color: yellow'>I  2 </td></tr>
<tr><td>15</td><td>5;0</td><td>2;0</td><td style='background-color: pink'>A  ?? </td><td style='background-color: yellow'>B  15 </td><td style='background-color: pink'>C  ?? </td><td style='background-color: pink'>D  ?? </td><td style='background-color: pink'>E  ?? </td><td style='background-color: pink'>F  ?? </td><td style='background-color: yellow'>G  3 </td><td style='background-color: yellow'>H  16 </td><td style='background-color: yellow'>I  187 </td></tr>
<tr><td>16</td><td>0;0</td><td>3;0</td><td style='background-color: pink'>A  ?? </td><td style='background-color: yellow'>B  16 </td><td style='background-color: pink'>C  ?? </td><td style='background-color: yellow'>D  15 </td><td style='background-color: pink'>E  ?? </td><td style='background-color: pink'>F  ?? </td><td style='background-color: yellow'>G  187 </td><td style='background-color: pink'>H  ?? </td><td style='background-color: yellow'>I  17 </td></tr>
<tr><td>17</td><td>1;0</td><td>4;0</td><td style='background-color: pink'>A  ?? </td><td style='background-color: yellow'>B  17 </td><td style='background-color: pink'>C  ?? </td><td style='background-color: yellow'>D  187 </td><td style='background-color: yellow'>E  16 </td><td style='background-color: pink'>F  ?? </td><td style='background-color: yellow'>G  1 </td><td style='background-color: pink'>H  ?? </td><td style='background-color: pink'>I  ?? </td></tr>
<tr><td>187</td><td>;0</td><td>;0</td><td style='background-color: lightgreen'>A  205 </td><td style='background-color: lightgreen'>B  187 </td><td style='background-color: lightgreen'>C  198 </td><td style='background-color: lightgreen'>D  3 </td><td style='background-color: lightgreen'>E  15 </td><td style='background-color: lightgreen'>F  16 </td><td style='background-color: lightgreen'>G  2 </td><td style='background-color: lightgreen'>H  17 </td><td style='background-color: lightgreen'>I  1 </td></tr>
<tr><td>198</td><td>;1</td><td>;5</td><td style='background-color: yellow'>A  187 </td><td style='background-color: yellow'>B  198 </td><td style='background-color: pink'>C  ?? </td><td style='background-color: pink'>D  ?? </td><td style='background-color: pink'>E  ?? </td><td style='background-color: pink'>F  ?? </td><td style='background-color: pink'>G  ?? </td><td style='background-color: pink'>H  ?? </td><td style='background-color: pink'>I  ?? </td></tr>
<tr><td>205</td><td>;5</td><td>;1</td><td style='background-color: pink'>A  ?? </td><td style='background-color: yellow'>B  205 </td><td style='background-color: yellow'>C  187 </td><td style='background-color: pink'>D  ?? </td><td style='background-color: pink'>E  ?? </td><td style='background-color: pink'>F  ?? </td><td style='background-color: pink'>G  ?? </td><td style='background-color: pink'>H  ?? </td><td style='background-color: pink'>I  ?? </td></tr>
<tr><td>223</td></tr>
</table>
<pre>
.                                -------
.                               /       \
.                              /         \
.                       -------           -------
.                      /       \         /       \
.                     /         \       /         \
.              -------           -------           -------
.             /       \         /       \         /       \
.            /         \       /         \       /         \
.     -------           -------           -------           -------
.    /       \         /       \         /       \         /       \
.   /         \       /         \       /         \       /         \
.  (           -------           -------           -------           )
.   \         /       \         /  <span style='background-color: pink'> 16</span>  \         /       \         /
.    \       /         \       /         \       /         \       /
.     -------           -------           -------           -------
.    /       \         /  <span style='background-color: pink'> 15</span>  \         /  <span style='background-color: pink'> 17</span>  \         /       \
.   /         \       /         \       /         \       /         \
.  (           -------           -------           -------           )
.   \         /       \         /  <span style='background-color: lightgreen'>187</span>  \         /       \         /
.    \       /         \       /<span style='background-color: pink'>205</span>   <span style='background-color: pink'>198</span>\       /         \       /
.     -------           -------           -------           -------
.    /       \         /  <span style='background-color: pink'> 3 </span>  \         /  <span style='background-color: pink'> 1 </span>  \         /       \
.   /         \       /         \       /         \       /         \
.  (           -------           -------           -------           )
.   \         /       \         /  <span style='background-color: pink'> 2 </span>  \         /       \         /
.    \       /         \       /         \       /         \       /
.     -------           -------           -------           -------
.    /       \         /       \         /       \         /       \
.   /         \       /         \       /         \       /         \
.  (           -------           -------           -------           )
.   \         /       \         /       \         /       \         /
.    \       /         \       /         \       /         \       /
.     -------           -------           -------           -------
.            \         /       \         /       \         /
.             \       /         \       /         \       /
.              -------           -------           -------
.                     \         /       \         /
.                      \       /         \       /
.                       -------           -------
.                              \         /
.                               \       /
.                                -------

</pre>

=end html
