-*- encoding: utf-8; indent-tabs-mode: nil -*-

=encoding utf-8

=head1 Explication / Explanation

Le programme C<aff.p6> génère un fichier HTML. Le problème est que Github affiche ces fichiers en
tant que fichiers sources et non pas en tant que document mis en forme. J'ai donc converti ce fichier
en fichier POD pour que Github l'affiche correctement. Il y a des problèmes néanmoins avec les styles
permettant d'afficher du texte sur un fond coloré. Vous pouvez toujours télécharger le fichier
HTML sur votre poste et l'afficher dans votre navigateur web.

The C<aff.p6> program generates an HTML file. The problem is that Github displays such files as
source files, not as real documents. So I have converted this HTML file into POD, so Github will
render it correctly. There is still a problem with the stylesheet which, in this case, is used to
change the background color for some texts. You can still download the HTML file and display it
with your favorite web browser.

=begin html

<table border='1'>
<tr><td>1</td><td>2;0</td><td>5;0</td><td class='hypoth'>A  8 </td><td class='hypoth'>B  1 </td><td class='hypoth'>C  12 </td><td class='hypoth'>D  2 </td><td class='hypoth'>E  187 </td><td class='hypoth'>F  17 </td><td class='hypoth'>G  37 </td><td class='hypoth'>H  70 </td><td class='hypoth'>I  60 </td></tr>
<tr><td>2</td><td>3;0</td><td>0;0</td><td class='hypoth'>A  9 </td><td class='hypoth'>B  2 </td><td class='hypoth'>C  31 </td><td class='hypoth'>D  86 </td><td class='hypoth'>E  3 </td><td class='hypoth'>F  187 </td><td class='hypoth'>G  96 </td><td class='hypoth'>H  1 </td><td class='hypoth'>I  37 </td></tr>
<tr><td>3</td><td>4;0</td><td>1;0</td><td class='hypoth'>A  22 </td><td class='hypoth'>B  3 </td><td class='hypoth'>C  36 </td><td class='hypoth'>D  75 </td><td class='hypoth'>E  76 </td><td class='hypoth'>F  15 </td><td class='hypoth'>G  86 </td><td class='hypoth'>H  187 </td><td class='hypoth'>I  2 </td></tr>
<tr><td>4</td><td>2;3</td><td>2;3</td><td class='hypoth'>A  33 </td><td class='hypoth'>B  4 </td><td class='hypoth'>C  14 </td><td class='hypoth'>D  101 </td><td class='hypoth'>E  89 </td><td class='hypoth'>F  78 </td><td class='hypoth'>G  21 </td><td class='hypoth'>H  5 </td><td class='hypoth'>I  188 </td></tr>
<tr><td>5</td><td>3;3</td><td>3;3</td><td class='certain'>A  32 </td><td class='certain'>B  5 </td><td class='certain'>C  28 </td><td class='certain'>D  4 </td><td class='certain'>E  78 </td><td class='certain'>F  67 </td><td class='certain'>G  188 </td><td class='certain'>H  57 </td><td class='certain'>I  6 </td></tr>
<tr><td>6</td><td>4;3</td><td>4;3</td><td class='hypoth'>A  25 </td><td class='hypoth'>B  6 </td><td class='hypoth'>C  29 </td><td class='hypoth'>D  188 </td><td class='hypoth'>E  5 </td><td class='hypoth'>F  57 </td><td class='hypoth'>G  19 </td><td class='hypoth'>H  46 </td><td class='hypoth'>I  105 </td></tr>
<tr><td>7</td><td>1;5</td><td>5;1</td><td class='hypoth'>A  13 </td><td class='hypoth'>B  7 </td><td class='hypoth'>C  17 </td><td class='hypoth'>D  8 </td><td class='hypoth'>E  205 </td><td class='hypoth'>F  24 </td><td class='hypoth'>G  49 </td><td class='hypoth'>H  82 </td><td class='hypoth'>I  71 </td></tr>
<tr><td>8</td><td>2;5</td><td>0;1</td><td class='hypoth'>A  14 </td><td class='hypoth'>B  8 </td><td class='hypoth'>C  1 </td><td class='hypoth'>D  97 </td><td class='hypoth'>E  9 </td><td class='hypoth'>F  205 </td><td class='hypoth'>G  38 </td><td class='hypoth'>H  7 </td><td class='hypoth'>I  49 </td></tr>
<tr><td>9</td><td>3;5</td><td>1;1</td><td class='hypoth'>A  28 </td><td class='hypoth'>B  9 </td><td class='hypoth'>C  2 </td><td class='hypoth'>D  87 </td><td class='hypoth'>E  88 </td><td class='hypoth'>F  22 </td><td class='hypoth'>G  97 </td><td class='hypoth'>H  205 </td><td class='hypoth'>I  8 </td></tr>
<tr><td>10</td><td>0;1</td><td>2;5</td><td class='hypoth'>A  16 </td><td class='hypoth'>B  10 </td><td class='hypoth'>C  27 </td><td class='hypoth'>D  53 </td><td class='hypoth'>E  42 </td><td class='hypoth'>F  102 </td><td class='hypoth'>G  35 </td><td class='hypoth'>H  11 </td><td class='hypoth'>I  198 </td></tr>
<tr><td>11</td><td>1;1</td><td>3;5</td><td class='certain'>A  17 </td><td class='certain'>B  11 </td><td class='certain'>C  34 </td><td class='certain'>D  10 </td><td class='certain'>E  102 </td><td class='certain'>F  103 </td><td class='certain'>G  198 </td><td class='certain'>H  80 </td><td class='certain'>I  12 </td></tr>
<tr><td>12</td><td>2;1</td><td>4;5</td><td class='hypoth'>A  1 </td><td class='hypoth'>B  12 </td><td class='hypoth'>C  33 </td><td class='hypoth'>D  198 </td><td class='hypoth'>E  11 </td><td class='hypoth'>F  80 </td><td class='hypoth'>G  31 </td><td class='hypoth'>H  69 </td><td class='hypoth'>I  59 </td></tr>
<tr><td>13</td><td>1;4</td><td>0;2</td><td class='hypoth'>A  21 </td><td class='hypoth'>B  13 </td><td class='hypoth'>C  7 </td><td class='hypoth'>D  39 </td><td class='hypoth'>E  14 </td><td class='hypoth'>F  213 </td><td class='hypoth'>G  50 </td><td class='hypoth'>H  18 </td><td class='hypoth'>I  61 </td></tr>
<tr><td>14</td><td>2;4</td><td>1;2</td><td class='hypoth'>A  4 </td><td class='hypoth'>B  14 </td><td class='hypoth'>C  8 </td><td class='hypoth'>D  98 </td><td class='hypoth'>E  99 </td><td class='hypoth'>F  28 </td><td class='hypoth'>G  39 </td><td class='hypoth'>H  213 </td><td class='hypoth'>I  13 </td></tr>
<tr><td>15</td><td>5;0</td><td>2;0</td><td class='hypoth'>A  23 </td><td class='hypoth'>B  15 </td><td class='hypoth'>C  35 </td><td class='hypoth'>D  76 </td><td class='hypoth'>E  54 </td><td class='hypoth'>F  43 </td><td class='hypoth'>G  3 </td><td class='hypoth'>H  16 </td><td class='hypoth'>I  187 </td></tr>
<tr><td>16</td><td>0;0</td><td>3;0</td><td class='certain'>A  24 </td><td class='certain'>B  16 </td><td class='certain'>C  10 </td><td class='certain'>D  15 </td><td class='certain'>E  43 </td><td class='certain'>F  91 </td><td class='certain'>G  187 </td><td class='certain'>H  107 </td><td class='certain'>I  17 </td></tr>
<tr><td>17</td><td>1;0</td><td>4;0</td><td class='hypoth'>A  7 </td><td class='hypoth'>B  17 </td><td class='hypoth'>C  11 </td><td class='hypoth'>D  187 </td><td class='hypoth'>E  16 </td><td class='hypoth'>F  107 </td><td class='hypoth'>G  1 </td><td class='hypoth'>H  81 </td><td class='hypoth'>I  70 </td></tr>
<tr><td>18</td><td>0;4</td><td>5;2</td><td class='hypoth'>A  20 </td><td class='hypoth'>B  18 </td><td class='hypoth'>C  24 </td><td class='hypoth'>D  13 </td><td class='hypoth'>E  213 </td><td class='hypoth'>F  30 </td><td class='hypoth'>G  61 </td><td class='hypoth'>H  94 </td><td class='hypoth'>I  83 </td></tr>
<tr><td>19</td><td>5;3</td><td>5;3</td><td class='hypoth'>A  26 </td><td class='hypoth'>B  19 </td><td class='hypoth'>C  30 </td><td class='hypoth'>D  20 </td><td class='hypoth'>E  188 </td><td class='hypoth'>F  6 </td><td class='hypoth'>G  72 </td><td class='hypoth'>H  105 </td><td class='hypoth'>I  106 </td></tr>
<tr><td>20</td><td>0;3</td><td>0;3</td><td class='hypoth'>A  27 </td><td class='hypoth'>B  20 </td><td class='hypoth'>C  18 </td><td class='hypoth'>D  51 </td><td class='hypoth'>E  21 </td><td class='hypoth'>F  188 </td><td class='hypoth'>G  62 </td><td class='hypoth'>H  19 </td><td class='hypoth'>I  72 </td></tr>
<tr><td>21</td><td>1;3</td><td>1;3</td><td class='hypoth'>A  34 </td><td class='hypoth'>B  21 </td><td class='hypoth'>C  13 </td><td class='hypoth'>D  40 </td><td class='hypoth'>E  101 </td><td class='hypoth'>F  4 </td><td class='hypoth'>G  51 </td><td class='hypoth'>H  188 </td><td class='hypoth'>I  20 </td></tr>
<tr><td>22</td><td>4;5</td><td>2;1</td><td class='hypoth'>A  29 </td><td class='hypoth'>B  22 </td><td class='hypoth'>C  3 </td><td class='hypoth'>D  88 </td><td class='hypoth'>E  65 </td><td class='hypoth'>F  55 </td><td class='hypoth'>G  9 </td><td class='hypoth'>H  23 </td><td class='hypoth'>I  205 </td></tr>
<tr><td>23</td><td>5;5</td><td>3;1</td><td class='certain'>A  30 </td><td class='certain'>B  23 </td><td class='certain'>C  15 </td><td class='certain'>D  22 </td><td class='certain'>E  55 </td><td class='certain'>F  44 </td><td class='certain'>G  205 </td><td class='certain'>H  92 </td><td class='certain'>I  24 </td></tr>
<tr><td>24</td><td>0;5</td><td>4;1</td><td class='hypoth'>A  18 </td><td class='hypoth'>B  24 </td><td class='hypoth'>C  16 </td><td class='hypoth'>D  205 </td><td class='hypoth'>E  23 </td><td class='hypoth'>F  92 </td><td class='hypoth'>G  7 </td><td class='hypoth'>H  93 </td><td class='hypoth'>I  82 </td></tr>
<tr><td>25</td><td>4;2</td><td>5;4</td><td class='hypoth'>A  36 </td><td class='hypoth'>B  25 </td><td class='hypoth'>C  6 </td><td class='hypoth'>D  26 </td><td class='hypoth'>E  209 </td><td class='hypoth'>F  32 </td><td class='hypoth'>G  84 </td><td class='hypoth'>H  47 </td><td class='hypoth'>I  108 </td></tr>
<tr><td>26</td><td>5;2</td><td>0;4</td><td class='hypoth'>A  35 </td><td class='hypoth'>B  26 </td><td class='hypoth'>C  19 </td><td class='hypoth'>D  63 </td><td class='hypoth'>E  27 </td><td class='hypoth'>F  209 </td><td class='hypoth'>G  73 </td><td class='hypoth'>H  25 </td><td class='hypoth'>I  84 </td></tr>
<tr><td>27</td><td>0;2</td><td>1;4</td><td class='hypoth'>A  10 </td><td class='hypoth'>B  27 </td><td class='hypoth'>C  20 </td><td class='hypoth'>D  52 </td><td class='hypoth'>E  41 </td><td class='hypoth'>F  34 </td><td class='hypoth'>G  63 </td><td class='hypoth'>H  209 </td><td class='hypoth'>I  26 </td></tr>
<tr><td>28</td><td>3;4</td><td>2;2</td><td class='hypoth'>A  5 </td><td class='hypoth'>B  28 </td><td class='hypoth'>C  9 </td><td class='hypoth'>D  99 </td><td class='hypoth'>E  77 </td><td class='hypoth'>F  66 </td><td class='hypoth'>G  14 </td><td class='hypoth'>H  29 </td><td class='hypoth'>I  213 </td></tr>
<tr><td>29</td><td>4;4</td><td>3;2</td><td class='certain'>A  6 </td><td class='certain'>B  29 </td><td class='certain'>C  22 </td><td class='certain'>D  28 </td><td class='certain'>E  66 </td><td class='certain'>F  56 </td><td class='certain'>G  213 </td><td class='certain'>H  45 </td><td class='certain'>I  30 </td></tr>
<tr><td>30</td><td>5;4</td><td>4;2</td><td class='hypoth'>A  19 </td><td class='hypoth'>B  30 </td><td class='hypoth'>C  23 </td><td class='hypoth'>D  213 </td><td class='hypoth'>E  29 </td><td class='hypoth'>F  45 </td><td class='hypoth'>G  18 </td><td class='hypoth'>H  104 </td><td class='hypoth'>I  94 </td></tr>
<tr><td>31</td><td>3;1</td><td>5;5</td><td class='hypoth'>A  2 </td><td class='hypoth'>B  31 </td><td class='hypoth'>C  32 </td><td class='hypoth'>D  36 </td><td class='hypoth'>E  198 </td><td class='hypoth'>F  12 </td><td class='hypoth'>G  95 </td><td class='hypoth'>H  59 </td><td class='hypoth'>I  48 </td></tr>
<tr><td>32</td><td>3;2</td><td>4;4</td><td class='hypoth'>A  31 </td><td class='hypoth'>B  32 </td><td class='hypoth'>C  5 </td><td class='hypoth'>D  209 </td><td class='hypoth'>E  33 </td><td class='hypoth'>F  68 </td><td class='hypoth'>G  25 </td><td class='hypoth'>H  58 </td><td class='hypoth'>I  47 </td></tr>
<tr><td>33</td><td>2;2</td><td>3;4</td><td class='certain'>A  12 </td><td class='certain'>B  33 </td><td class='certain'>C  4 </td><td class='certain'>D  34 </td><td class='certain'>E  90 </td><td class='certain'>F  79 </td><td class='certain'>G  209 </td><td class='certain'>H  68 </td><td class='certain'>I  32 </td></tr>
<tr><td>34</td><td>1;2</td><td>2;4</td><td class='hypoth'>A  11 </td><td class='hypoth'>B  34 </td><td class='hypoth'>C  21 </td><td class='hypoth'>D  41 </td><td class='hypoth'>E  100 </td><td class='hypoth'>F  90 </td><td class='hypoth'>G  27 </td><td class='hypoth'>H  33 </td><td class='hypoth'>I  209 </td></tr>
<tr><td>35</td><td>5;1</td><td>1;5</td><td class='hypoth'>A  15 </td><td class='hypoth'>B  35 </td><td class='hypoth'>C  26 </td><td class='hypoth'>D  64 </td><td class='hypoth'>E  53 </td><td class='hypoth'>F  10 </td><td class='hypoth'>G  74 </td><td class='hypoth'>H  198 </td><td class='hypoth'>I  36 </td></tr>
<tr><td>36</td><td>4;1</td><td>0;5</td><td class='hypoth'>A  3 </td><td class='hypoth'>B  36 </td><td class='hypoth'>C  25 </td><td class='hypoth'>D  74 </td><td class='hypoth'>E  35 </td><td class='hypoth'>F  198 </td><td class='hypoth'>G  85 </td><td class='hypoth'>H  31 </td><td class='hypoth'>I  95 </td></tr>
<tr><td>37</td><td>23;0</td><td>05;0</td><td class='hypoth'>A  97 </td><td class='hypoth'>B  37 </td><td class='hypoth'>C  59 </td><td class='hypoth'>D  96 </td><td class='hypoth'>E  2 </td><td class='hypoth'>F  1 </td><td class='hypoth'>G  115 </td><td class='hypoth'>H  60 </td><td class='hypoth'>I  180 </td></tr>
<tr><td>38</td><td>22;5</td><td>00;1</td><td class='certain'>A  98 </td><td class='certain'>B  38 </td><td class='certain'>C  60 </td><td class='certain'>D  123 </td><td class='certain'>E  97 </td><td class='certain'>F  8 </td><td class='certain'>G  122 </td><td class='certain'>H  49 </td><td class='certain'>I  121 </td></tr>
<tr><td>39</td><td>12;4</td><td>01;2</td><td class='hypoth'>A  101 </td><td class='hypoth'>B  39 </td><td class='hypoth'>C  49 </td><td class='hypoth'>D  160 </td><td class='hypoth'>E  98 </td><td class='hypoth'>F  14 </td><td class='hypoth'>G  129 </td><td class='hypoth'>H  13 </td><td class='hypoth'>I  50 </td></tr>
<tr><td>40</td><td>11;3</td><td>11;3</td><td class='certain'>A  100 </td><td class='certain'>B  40 </td><td class='certain'>C  50 </td><td class='certain'>D  167 </td><td class='certain'>E  168 </td><td class='certain'>F  101 </td><td class='certain'>G  166 </td><td class='certain'>H  21 </td><td class='certain'>I  51 </td></tr>
<tr><td>41</td><td>01;2</td><td>12;4</td><td class='hypoth'>A  102 </td><td class='hypoth'>B  41 </td><td class='hypoth'>C  51 </td><td class='hypoth'>D  132 </td><td class='hypoth'>E  163 </td><td class='hypoth'>F  100 </td><td class='hypoth'>G  52 </td><td class='hypoth'>H  34 </td><td class='hypoth'>I  27 </td></tr>
<tr><td>42</td><td>00;1</td><td>22;5</td><td class='certain'>A  91 </td><td class='certain'>B  42 </td><td class='certain'>C  52 </td><td class='certain'>D  124 </td><td class='certain'>E  125 </td><td class='certain'>F  126 </td><td class='certain'>G  53 </td><td class='certain'>H  102 </td><td class='certain'>I  10 </td></tr>
<tr><td>43</td><td>05;0</td><td>23;0</td><td class='hypoth'>A  92 </td><td class='hypoth'>B  43 </td><td class='hypoth'>C  53 </td><td class='hypoth'>D  54 </td><td class='hypoth'>E  177 </td><td class='hypoth'>F  118 </td><td class='hypoth'>G  15 </td><td class='hypoth'>H  91 </td><td class='hypoth'>I  16 </td></tr>
<tr><td>44</td><td>55;5</td><td>33;1</td><td class='certain'>A  104 </td><td class='certain'>B  44 </td><td class='certain'>C  54 </td><td class='certain'>D  55 </td><td class='certain'>E  199 </td><td class='certain'>F  200 </td><td class='certain'>G  23 </td><td class='certain'>H  201 </td><td class='certain'>I  92 </td></tr>
<tr><td>45</td><td>45;4</td><td>34;2</td><td class='hypoth'>A  105 </td><td class='hypoth'>B  45 </td><td class='hypoth'>C  55 </td><td class='hypoth'>D  29 </td><td class='hypoth'>E  56 </td><td class='hypoth'>F  208 </td><td class='hypoth'>G  30 </td><td class='hypoth'>H  217 </td><td class='hypoth'>I  104 </td></tr>
<tr><td>46</td><td>44;3</td><td>44;3</td><td class='certain'>A  108 </td><td class='certain'>B  46 </td><td class='certain'>C  56 </td><td class='certain'>D  6 </td><td class='certain'>E  57 </td><td class='certain'>F  109 </td><td class='certain'>G  105 </td><td class='certain'>H  110 </td><td class='certain'>I  111 </td></tr>
<tr><td>47</td><td>34;2</td><td>45;4</td><td class='hypoth'>A  95 </td><td class='hypoth'>B  47 </td><td class='hypoth'>C  57 </td><td class='hypoth'>D  25 </td><td class='hypoth'>E  32 </td><td class='hypoth'>F  58 </td><td class='hypoth'>G  108 </td><td class='hypoth'>H  212 </td><td class='hypoth'>I  220 </td></tr>
<tr><td>48</td><td>33;1</td><td>55;5</td><td class='certain'>A  96 </td><td class='certain'>B  48 </td><td class='certain'>C  58 </td><td class='certain'>D  95 </td><td class='certain'>E  31 </td><td class='certain'>F  59 </td><td class='certain'>G  204 </td><td class='certain'>H  202 </td><td class='certain'>I  203 </td></tr>
<tr><td>49</td><td>12;5</td><td>05;1</td><td class='hypoth'>A  39 </td><td class='hypoth'>B  49 </td><td class='hypoth'>C  70 </td><td class='hypoth'>D  38 </td><td class='hypoth'>E  8 </td><td class='hypoth'>F  7 </td><td class='hypoth'>G  121 </td><td class='hypoth'>H  71 </td><td class='hypoth'>I  174 </td></tr>
<tr><td>50</td><td>11;4</td><td>00;2</td><td class='certain'>A  40 </td><td class='certain'>B  50 </td><td class='certain'>C  71 </td><td class='certain'>D  129 </td><td class='certain'>E  39 </td><td class='certain'>F  13 </td><td class='certain'>G  128 </td><td class='certain'>H  61 </td><td class='certain'>I  127 </td></tr>
<tr><td>51</td><td>01;3</td><td>01;3</td><td class='hypoth'>A  41 </td><td class='hypoth'>B  51 </td><td class='hypoth'>C  61 </td><td class='hypoth'>D  166 </td><td class='hypoth'>E  40 </td><td class='hypoth'>F  21 </td><td class='hypoth'>G  135 </td><td class='hypoth'>H  20 </td><td class='hypoth'>I  62 </td></tr>
<tr><td>52</td><td>00;2</td><td>11;4</td><td class='certain'>A  42 </td><td class='certain'>B  52 </td><td class='certain'>C  62 </td><td class='certain'>D  131 </td><td class='certain'>E  132 </td><td class='certain'>F  41 </td><td class='certain'>G  130 </td><td class='certain'>H  27 </td><td class='certain'>I  63 </td></tr>
<tr><td>53</td><td>05;1</td><td>12;5</td><td class='hypoth'>A  43 </td><td class='hypoth'>B  53 </td><td class='hypoth'>C  63 </td><td class='hypoth'>D  171 </td><td class='hypoth'>E  124 </td><td class='hypoth'>F  42 </td><td class='hypoth'>G  64 </td><td class='hypoth'>H  10 </td><td class='hypoth'>I  35 </td></tr>
<tr><td>54</td><td>55;0</td><td>22;0</td><td class='certain'>A  44 </td><td class='certain'>B  54 </td><td class='certain'>C  64 </td><td class='certain'>D  175 </td><td class='certain'>E  176 </td><td class='certain'>F  177 </td><td class='certain'>G  76 </td><td class='certain'>H  43 </td><td class='certain'>I  15 </td></tr>
<tr><td>55</td><td>45;5</td><td>23;1</td><td class='hypoth'>A  45 </td><td class='hypoth'>B  55 </td><td class='hypoth'>C  76 </td><td class='hypoth'>D  65 </td><td class='hypoth'>E  183 </td><td class='hypoth'>F  199 </td><td class='hypoth'>G  22 </td><td class='hypoth'>H  44 </td><td class='hypoth'>I  23 </td></tr>
<tr><td>56</td><td>44;4</td><td>33;2</td><td class='certain'>A  46 </td><td class='certain'>B  56 </td><td class='certain'>C  65 </td><td class='certain'>D  66 </td><td class='certain'>E  206 </td><td class='certain'>F  207 </td><td class='certain'>G  29 </td><td class='certain'>H  208 </td><td class='certain'>I  45 </td></tr>
<tr><td>57</td><td>34;3</td><td>34;3</td><td class='hypoth'>A  47 </td><td class='hypoth'>B  57 </td><td class='hypoth'>C  66 </td><td class='hypoth'>D  5 </td><td class='hypoth'>E  67 </td><td class='hypoth'>F  216 </td><td class='hypoth'>G  6 </td><td class='hypoth'>H  109 </td><td class='hypoth'>I  46 </td></tr>
<tr><td>58</td><td>33;2</td><td>44;4</td><td class='certain'>A  48 </td><td class='certain'>B  58 </td><td class='certain'>C  67 </td><td class='certain'>D  32 </td><td class='certain'>E  68 </td><td class='certain'>F  210 </td><td class='certain'>G  47 </td><td class='certain'>H  211 </td><td class='certain'>I  212 </td></tr>
<tr><td>59</td><td>23;1</td><td>45;5</td><td class='hypoth'>A  37 </td><td class='hypoth'>B  59 </td><td class='hypoth'>C  68 </td><td class='hypoth'>D  31 </td><td class='hypoth'>E  12 </td><td class='hypoth'>F  69 </td><td class='hypoth'>G  48 </td><td class='hypoth'>H  186 </td><td class='hypoth'>I  202 </td></tr>
<tr><td>60</td><td>22;0</td><td>55;0</td><td class='certain'>A  38 </td><td class='certain'>B  60 </td><td class='certain'>C  69 </td><td class='certain'>D  37 </td><td class='certain'>E  1 </td><td class='certain'>F  70 </td><td class='certain'>G  180 </td><td class='certain'>H  178 </td><td class='certain'>I  179 </td></tr>
<tr><td>61</td><td>01;4</td><td>05;2</td><td class='hypoth'>A  51 </td><td class='hypoth'>B  61 </td><td class='hypoth'>C  82 </td><td class='hypoth'>D  50 </td><td class='hypoth'>E  13 </td><td class='hypoth'>F  18 </td><td class='hypoth'>G  127 </td><td class='hypoth'>H  83 </td><td class='hypoth'>I  141 </td></tr>
<tr><td>62</td><td>00;3</td><td>00;3</td><td class='certain'>A  52 </td><td class='certain'>B  62 </td><td class='certain'>C  83 </td><td class='certain'>D  135 </td><td class='certain'>E  51 </td><td class='certain'>F  20 </td><td class='certain'>G  134 </td><td class='certain'>H  72 </td><td class='certain'>I  133 </td></tr>
<tr><td>63</td><td>05;2</td><td>01;4</td><td class='hypoth'>A  53 </td><td class='hypoth'>B  63 </td><td class='hypoth'>C  72 </td><td class='hypoth'>D  130 </td><td class='hypoth'>E  52 </td><td class='hypoth'>F  27 </td><td class='hypoth'>G  138 </td><td class='hypoth'>H  26 </td><td class='hypoth'>I  73 </td></tr>
<tr><td>64</td><td>55;1</td><td>11;5</td><td class='certain'>A  54 </td><td class='certain'>B  64 </td><td class='certain'>C  73 </td><td class='certain'>D  170 </td><td class='certain'>E  171 </td><td class='certain'>F  53 </td><td class='certain'>G  169 </td><td class='certain'>H  35 </td><td class='certain'>I  74 </td></tr>
<tr><td>65</td><td>44;5</td><td>22;1</td><td class='certain'>A  56 </td><td class='certain'>B  65 </td><td class='certain'>C  75 </td><td class='certain'>D  181 </td><td class='certain'>E  182 </td><td class='certain'>F  183 </td><td class='certain'>G  88 </td><td class='certain'>H  55 </td><td class='certain'>I  22 </td></tr>
<tr><td>66</td><td>34;4</td><td>23;2</td><td class='hypoth'>A  57 </td><td class='hypoth'>B  66 </td><td class='hypoth'>C  88 </td><td class='hypoth'>D  77 </td><td class='hypoth'>E  191 </td><td class='hypoth'>F  206 </td><td class='hypoth'>G  28 </td><td class='hypoth'>H  56 </td><td class='hypoth'>I  29 </td></tr>
<tr><td>67</td><td>33;3</td><td>33;3</td><td class='certain'>A  58 </td><td class='certain'>B  67 </td><td class='certain'>C  77 </td><td class='certain'>D  78 </td><td class='certain'>E  214 </td><td class='certain'>F  215 </td><td class='certain'>G  5 </td><td class='certain'>H  216 </td><td class='certain'>I  57 </td></tr>
<tr><td>68</td><td>23;2</td><td>34;4</td><td class='hypoth'>A  59 </td><td class='hypoth'>B  68 </td><td class='hypoth'>C  78 </td><td class='hypoth'>D  33 </td><td class='hypoth'>E  79 </td><td class='hypoth'>F  194 </td><td class='hypoth'>G  32 </td><td class='hypoth'>H  210 </td><td class='hypoth'>I  58 </td></tr>
<tr><td>69</td><td>22;1</td><td>44;5</td><td class='certain'>A  60 </td><td class='certain'>B  69 </td><td class='certain'>C  79 </td><td class='certain'>D  12 </td><td class='certain'>E  80 </td><td class='certain'>F  184 </td><td class='certain'>G  59 </td><td class='certain'>H  185 </td><td class='certain'>I  186 </td></tr>
<tr><td>70</td><td>12;0</td><td>45;0</td><td class='hypoth'>A  49 </td><td class='hypoth'>B  70 </td><td class='hypoth'>C  80 </td><td class='hypoth'>D  1 </td><td class='hypoth'>E  17 </td><td class='hypoth'>F  81 </td><td class='hypoth'>G  60 </td><td class='hypoth'>H  153 </td><td class='hypoth'>I  178 </td></tr>
<tr><td>71</td><td>11;5</td><td>55;1</td><td class='certain'>A  50 </td><td class='certain'>B  71 </td><td class='certain'>C  81 </td><td class='certain'>D  49 </td><td class='certain'>E  7 </td><td class='certain'>F  82 </td><td class='certain'>G  174 </td><td class='certain'>H  172 </td><td class='certain'>I  173 </td></tr>
<tr><td>72</td><td>05;3</td><td>05;3</td><td class='hypoth'>A  63 </td><td class='hypoth'>B  72 </td><td class='hypoth'>C  94 </td><td class='hypoth'>D  62 </td><td class='hypoth'>E  20 </td><td class='hypoth'>F  19 </td><td class='hypoth'>G  133 </td><td class='hypoth'>H  106 </td><td class='hypoth'>I  114 </td></tr>
<tr><td>73</td><td>55;2</td><td>00;4</td><td class='certain'>A  64 </td><td class='certain'>B  73 </td><td class='certain'>C  106 </td><td class='certain'>D  138 </td><td class='certain'>E  63 </td><td class='certain'>F  26 </td><td class='certain'>G  137 </td><td class='certain'>H  84 </td><td class='certain'>I  136 </td></tr>
<tr><td>74</td><td>45;1</td><td>01;5</td><td class='hypoth'>A  76 </td><td class='hypoth'>B  74 </td><td class='hypoth'>C  84 </td><td class='hypoth'>D  169 </td><td class='hypoth'>E  64 </td><td class='hypoth'>F  35 </td><td class='hypoth'>G  144 </td><td class='hypoth'>H  36 </td><td class='hypoth'>I  85 </td></tr>
<tr><td>75</td><td>44;0</td><td>11;0</td><td class='certain'>A  65 </td><td class='certain'>B  75 </td><td class='certain'>C  85 </td><td class='certain'>D  149 </td><td class='certain'>E  150 </td><td class='certain'>F  76 </td><td class='certain'>G  148 </td><td class='certain'>H  3 </td><td class='certain'>I  86 </td></tr>
<tr><td>76</td><td>45;0</td><td>12;0</td><td class='hypoth'>A  55 </td><td class='hypoth'>B  76 </td><td class='hypoth'>C  74 </td><td class='hypoth'>D  150 </td><td class='hypoth'>E  175 </td><td class='hypoth'>F  54 </td><td class='hypoth'>G  75 </td><td class='hypoth'>H  15 </td><td class='hypoth'>I  3 </td></tr>
<tr><td>77</td><td>33;4</td><td>22;2</td><td class='certain'>A  67 </td><td class='certain'>B  77 </td><td class='certain'>C  87 </td><td class='certain'>D  189 </td><td class='certain'>E  190 </td><td class='certain'>F  191 </td><td class='certain'>G  99 </td><td class='certain'>H  66 </td><td class='certain'>I  28 </td></tr>
<tr><td>78</td><td>23;3</td><td>23;3</td><td class='hypoth'>A  68 </td><td class='hypoth'>B  78 </td><td class='hypoth'>C  99 </td><td class='hypoth'>D  89 </td><td class='hypoth'>E  197 </td><td class='hypoth'>F  214 </td><td class='hypoth'>G  4 </td><td class='hypoth'>H  67 </td><td class='hypoth'>I  5 </td></tr>
<tr><td>79</td><td>22;2</td><td>33;4</td><td class='certain'>A  69 </td><td class='certain'>B  79 </td><td class='certain'>C  89 </td><td class='certain'>D  90 </td><td class='certain'>E  192 </td><td class='certain'>F  193 </td><td class='certain'>G  33 </td><td class='certain'>H  194 </td><td class='certain'>I  68 </td></tr>
<tr><td>80</td><td>12;1</td><td>34;5</td><td class='hypoth'>A  70 </td><td class='hypoth'>B  80 </td><td class='hypoth'>C  90 </td><td class='hypoth'>D  11 </td><td class='hypoth'>E  103 </td><td class='hypoth'>F  159 </td><td class='hypoth'>G  12 </td><td class='hypoth'>H  184 </td><td class='hypoth'>I  69 </td></tr>
<tr><td>81</td><td>11;0</td><td>44;0</td><td class='certain'>A  71 </td><td class='certain'>B  81 </td><td class='certain'>C  103 </td><td class='certain'>D  17 </td><td class='certain'>E  107 </td><td class='certain'>F  151 </td><td class='certain'>G  70 </td><td class='certain'>H  152 </td><td class='certain'>I  153 </td></tr>
<tr><td>82</td><td>01;5</td><td>45;1</td><td class='hypoth'>A  61 </td><td class='hypoth'>B  82 </td><td class='hypoth'>C  107 </td><td class='hypoth'>D  7 </td><td class='hypoth'>E  24 </td><td class='hypoth'>F  93 </td><td class='hypoth'>G  71 </td><td class='hypoth'>H  147 </td><td class='hypoth'>I  172 </td></tr>
<tr><td>83</td><td>00;4</td><td>55;2</td><td class='certain'>A  62 </td><td class='certain'>B  83 </td><td class='certain'>C  93 </td><td class='certain'>D  61 </td><td class='certain'>E  18 </td><td class='certain'>F  94 </td><td class='certain'>G  141 </td><td class='certain'>H  139 </td><td class='certain'>I  140 </td></tr>
<tr><td>84</td><td>45;2</td><td>05;4</td><td class='hypoth'>A  74 </td><td class='hypoth'>B  84 </td><td class='hypoth'>C  105 </td><td class='hypoth'>D  73 </td><td class='hypoth'>E  26 </td><td class='hypoth'>F  25 </td><td class='hypoth'>G  136 </td><td class='hypoth'>H  108 </td><td class='hypoth'>I  222 </td></tr>
<tr><td>85</td><td>44;1</td><td>00;5</td><td class='certain'>A  75 </td><td class='certain'>B  85 </td><td class='certain'>C  108 </td><td class='certain'>D  144 </td><td class='certain'>E  74 </td><td class='certain'>F  36 </td><td class='certain'>G  143 </td><td class='certain'>H  95 </td><td class='certain'>I  142 </td></tr>
<tr><td>86</td><td>34;0</td><td>01;0</td><td class='hypoth'>A  88 </td><td class='hypoth'>B  86 </td><td class='hypoth'>C  95 </td><td class='hypoth'>D  148 </td><td class='hypoth'>E  75 </td><td class='hypoth'>F  3 </td><td class='hypoth'>G  117 </td><td class='hypoth'>H  2 </td><td class='hypoth'>I  96 </td></tr>
<tr><td>87</td><td>33;5</td><td>11;1</td><td class='certain'>A  77 </td><td class='certain'>B  87 </td><td class='certain'>C  96 </td><td class='certain'>D  155 </td><td class='certain'>E  156 </td><td class='certain'>F  88 </td><td class='certain'>G  154 </td><td class='certain'>H  9 </td><td class='certain'>I  97 </td></tr>
<tr><td>88</td><td>34;5</td><td>12;1</td><td class='hypoth'>A  66 </td><td class='hypoth'>B  88 </td><td class='hypoth'>C  86 </td><td class='hypoth'>D  156 </td><td class='hypoth'>E  181 </td><td class='hypoth'>F  65 </td><td class='hypoth'>G  87 </td><td class='hypoth'>H  22 </td><td class='hypoth'>I  9 </td></tr>
<tr><td>89</td><td>22;3</td><td>22;3</td><td class='certain'>A  79 </td><td class='certain'>B  89 </td><td class='certain'>C  98 </td><td class='certain'>D  195 </td><td class='certain'>E  196 </td><td class='certain'>F  197 </td><td class='certain'>G  101 </td><td class='certain'>H  78 </td><td class='certain'>I  4 </td></tr>
<tr><td>90</td><td>12;2</td><td>23;4</td><td class='hypoth'>A  80 </td><td class='hypoth'>B  90 </td><td class='hypoth'>C  101 </td><td class='hypoth'>D  100 </td><td class='hypoth'>E  165 </td><td class='hypoth'>F  192 </td><td class='hypoth'>G  34 </td><td class='hypoth'>H  79 </td><td class='hypoth'>I  33 </td></tr>
<tr><td>91</td><td>00;0</td><td>33;0</td><td class='certain'>A  93 </td><td class='certain'>B  91 </td><td class='certain'>C  42 </td><td class='certain'>D  43 </td><td class='certain'>E  118 </td><td class='certain'>F  119 </td><td class='certain'>G  16 </td><td class='certain'>H  120 </td><td class='certain'>I  107 </td></tr>
<tr><td>92</td><td>05;5</td><td>34;1</td><td class='hypoth'>A  94 </td><td class='hypoth'>B  92 </td><td class='hypoth'>C  43 </td><td class='hypoth'>D  23 </td><td class='hypoth'>E  44 </td><td class='hypoth'>F  201 </td><td class='hypoth'>G  24 </td><td class='hypoth'>H  145 </td><td class='hypoth'>I  93 </td></tr>
<tr><td>93</td><td>00;5</td><td>44;1</td><td class='certain'>A  83 </td><td class='certain'>B  93 </td><td class='certain'>C  91 </td><td class='certain'>D  24 </td><td class='certain'>E  92 </td><td class='certain'>F  145 </td><td class='certain'>G  82 </td><td class='certain'>H  146 </td><td class='certain'>I  147 </td></tr>
<tr><td>94</td><td>05;4</td><td>45;2</td><td class='hypoth'>A  72 </td><td class='hypoth'>B  94 </td><td class='hypoth'>C  92 </td><td class='hypoth'>D  18 </td><td class='hypoth'>E  30 </td><td class='hypoth'>F  104 </td><td class='hypoth'>G  83 </td><td class='hypoth'>H  219 </td><td class='hypoth'>I  139 </td></tr>
<tr><td>95</td><td>34;1</td><td>05;5</td><td class='hypoth'>A  86 </td><td class='hypoth'>B  95 </td><td class='hypoth'>C  47 </td><td class='hypoth'>D  85 </td><td class='hypoth'>E  36 </td><td class='hypoth'>F  31 </td><td class='hypoth'>G  142 </td><td class='hypoth'>H  48 </td><td class='hypoth'>I  204 </td></tr>
<tr><td>96</td><td>33;0</td><td>00;0</td><td class='certain'>A  87 </td><td class='certain'>B  96 </td><td class='certain'>C  48 </td><td class='certain'>D  117 </td><td class='certain'>E  86 </td><td class='certain'>F  2 </td><td class='certain'>G  116 </td><td class='certain'>H  37 </td><td class='certain'>I  115 </td></tr>
<tr><td>97</td><td>23;5</td><td>01;1</td><td class='hypoth'>A  99 </td><td class='hypoth'>B  97 </td><td class='hypoth'>C  37 </td><td class='hypoth'>D  154 </td><td class='hypoth'>E  87 </td><td class='hypoth'>F  9 </td><td class='hypoth'>G  123 </td><td class='hypoth'>H  8 </td><td class='hypoth'>I  38 </td></tr>
<tr><td>98</td><td>22;4</td><td>11;2</td><td class='certain'>A  89 </td><td class='certain'>B  98 </td><td class='certain'>C  38 </td><td class='certain'>D  161 </td><td class='certain'>E  162 </td><td class='certain'>F  99 </td><td class='certain'>G  160 </td><td class='certain'>H  14 </td><td class='certain'>I  39 </td></tr>
<tr><td>99</td><td>23;4</td><td>12;2</td><td class='hypoth'>A  78 </td><td class='hypoth'>B  99 </td><td class='hypoth'>C  97 </td><td class='hypoth'>D  162 </td><td class='hypoth'>E  189 </td><td class='hypoth'>F  77 </td><td class='hypoth'>G  98 </td><td class='hypoth'>H  28 </td><td class='hypoth'>I  14 </td></tr>
<tr><td>100</td><td>11;2</td><td>22;4</td><td class='certain'>A  103 </td><td class='certain'>B  100 </td><td class='certain'>C  40 </td><td class='certain'>D  163 </td><td class='certain'>E  164 </td><td class='certain'>F  165 </td><td class='certain'>G  41 </td><td class='certain'>H  90 </td><td class='certain'>I  34 </td></tr>
<tr><td>101</td><td>12;3</td><td>12;3</td><td class='hypoth'>A  90 </td><td class='hypoth'>B  101 </td><td class='hypoth'>C  39 </td><td class='hypoth'>D  168 </td><td class='hypoth'>E  195 </td><td class='hypoth'>F  89 </td><td class='hypoth'>G  40 </td><td class='hypoth'>H  4 </td><td class='hypoth'>I  21 </td></tr>
<tr><td>102</td><td>01;1</td><td>23;5</td><td class='hypoth'>A  107 </td><td class='hypoth'>B  102 </td><td class='hypoth'>C  41 </td><td class='hypoth'>D  42 </td><td class='hypoth'>E  126 </td><td class='hypoth'>F  157 </td><td class='hypoth'>G  10 </td><td class='hypoth'>H  103 </td><td class='hypoth'>I  11 </td></tr>
<tr><td>103</td><td>11;1</td><td>33;5</td><td class='certain'>A  81 </td><td class='certain'>B  103 </td><td class='certain'>C  100 </td><td class='certain'>D  102 </td><td class='certain'>E  157 </td><td class='certain'>F  158 </td><td class='certain'>G  11 </td><td class='certain'>H  159 </td><td class='certain'>I  80 </td></tr>
<tr><td>104</td><td>55;4</td><td>44;2</td><td class='certain'>A  106 </td><td class='certain'>B  104 </td><td class='certain'>C  44 </td><td class='certain'>D  30 </td><td class='certain'>E  45 </td><td class='certain'>F  217 </td><td class='certain'>G  94 </td><td class='certain'>H  218 </td><td class='certain'>I  219 </td></tr>
<tr><td>105</td><td>45;3</td><td>45;3</td><td class='hypoth'>A  84 </td><td class='hypoth'>B  105 </td><td class='hypoth'>C  45 </td><td class='hypoth'>D  19 </td><td class='hypoth'>E  6 </td><td class='hypoth'>F  46 </td><td class='hypoth'>G  106 </td><td class='hypoth'>H  111 </td><td class='hypoth'>I  112 </td></tr>
<tr><td>106</td><td>55;3</td><td>55;3</td><td class='certain'>A  73 </td><td class='certain'>B  106 </td><td class='certain'>C  104 </td><td class='certain'>D  72 </td><td class='certain'>E  19 </td><td class='certain'>F  105 </td><td class='certain'>G  114 </td><td class='certain'>H  112 </td><td class='certain'>I  113 </td></tr>
<tr><td>107</td><td>01;0</td><td>34;0</td><td class='hypoth'>A  82 </td><td class='hypoth'>B  107 </td><td class='hypoth'>C  102 </td><td class='hypoth'>D  16 </td><td class='hypoth'>E  91 </td><td class='hypoth'>F  120 </td><td class='hypoth'>G  17 </td><td class='hypoth'>H  151 </td><td class='hypoth'>I  81 </td></tr>
<tr><td>108</td><td>44;2</td><td>55;4</td><td class='certain'>A  85 </td><td class='certain'>B  108 </td><td class='certain'>C  46 </td><td class='certain'>D  84 </td><td class='certain'>E  25 </td><td class='certain'>F  47 </td><td class='certain'>G  222 </td><td class='certain'>H  220 </td><td class='certain'>I  221 </td></tr>
<tr><td>109</td><td>344;3</td><td>344;3</td><td class='hypoth'>A  220 </td><td class='hypoth'>B  109 </td><td class='hypoth'>C  206 </td><td class='hypoth'>D  57 </td><td class='hypoth'>E  216 </td><td class='hypoth'>F  223 </td><td class='hypoth'>G  46 </td><td class='hypoth'>H  223 </td><td class='hypoth'>I  110 </td></tr>
<tr><td>110</td><td>444;3</td><td>444;3</td><td class='hypoth'>A  221 </td><td class='hypoth'>B  110 </td><td class='hypoth'>C  207 </td><td class='hypoth'>D  46 </td><td class='hypoth'>E  109 </td><td class='hypoth'>F  223 </td><td class='hypoth'>G  111 </td><td class='hypoth'>H  223 </td><td class='hypoth'>I  223 </td></tr>
<tr><td>111</td><td>445;3</td><td>445;3</td><td class='hypoth'>A  222 </td><td class='hypoth'>B  111 </td><td class='hypoth'>C  208 </td><td class='hypoth'>D  105 </td><td class='hypoth'>E  46 </td><td class='hypoth'>F  110 </td><td class='hypoth'>G  112 </td><td class='hypoth'>H  223 </td><td class='hypoth'>I  223 </td></tr>
<tr><td>112</td><td>455;3</td><td>455;3</td><td class='hypoth'>A  136 </td><td class='hypoth'>B  112 </td><td class='hypoth'>C  217 </td><td class='hypoth'>D  106 </td><td class='hypoth'>E  105 </td><td class='hypoth'>F  111 </td><td class='hypoth'>G  113 </td><td class='hypoth'>H  223 </td><td class='hypoth'>I  223 </td></tr>
<tr><td>113</td><td>555;3</td><td>555;3</td><td class='hypoth'>A  137 </td><td class='hypoth'>B  113 </td><td class='hypoth'>C  218 </td><td class='hypoth'>D  114 </td><td class='hypoth'>E  106 </td><td class='hypoth'>F  112 </td><td class='hypoth'>G  223 </td><td class='hypoth'>H  223 </td><td class='hypoth'>I  223 </td></tr>
<tr><td>114</td><td>055;3</td><td>055;3</td><td class='hypoth'>A  138 </td><td class='hypoth'>B  114 </td><td class='hypoth'>C  219 </td><td class='hypoth'>D  133 </td><td class='hypoth'>E  72 </td><td class='hypoth'>F  106 </td><td class='hypoth'>G  223 </td><td class='hypoth'>H  113 </td><td class='hypoth'>I  223 </td></tr>
<tr><td>115</td><td>233;0</td><td>005;0</td><td class='hypoth'>A  154 </td><td class='hypoth'>B  115 </td><td class='hypoth'>C  202 </td><td class='hypoth'>D  116 </td><td class='hypoth'>E  96 </td><td class='hypoth'>F  37 </td><td class='hypoth'>G  223 </td><td class='hypoth'>H  180 </td><td class='hypoth'>I  223 </td></tr>
<tr><td>116</td><td>333;0</td><td>000;0</td><td class='hypoth'>A  155 </td><td class='hypoth'>B  116 </td><td class='hypoth'>C  203 </td><td class='hypoth'>D  223 </td><td class='hypoth'>E  117 </td><td class='hypoth'>F  96 </td><td class='hypoth'>G  223 </td><td class='hypoth'>H  115 </td><td class='hypoth'>I  223 </td></tr>
<tr><td>117</td><td>334;0</td><td>001;0</td><td class='hypoth'>A  156 </td><td class='hypoth'>B  117 </td><td class='hypoth'>C  204 </td><td class='hypoth'>D  223 </td><td class='hypoth'>E  148 </td><td class='hypoth'>F  86 </td><td class='hypoth'>G  223 </td><td class='hypoth'>H  96 </td><td class='hypoth'>I  116 </td></tr>
<tr><td>118</td><td>005;0</td><td>233;0</td><td class='hypoth'>A  145 </td><td class='hypoth'>B  118 </td><td class='hypoth'>C  124 </td><td class='hypoth'>D  177 </td><td class='hypoth'>E  223 </td><td class='hypoth'>F  223 </td><td class='hypoth'>G  43 </td><td class='hypoth'>H  119 </td><td class='hypoth'>I  91 </td></tr>
<tr><td>119</td><td>000;0</td><td>333;0</td><td class='hypoth'>A  146 </td><td class='hypoth'>B  119 </td><td class='hypoth'>C  125 </td><td class='hypoth'>D  118 </td><td class='hypoth'>E  223 </td><td class='hypoth'>F  223 </td><td class='hypoth'>G  91 </td><td class='hypoth'>H  223 </td><td class='hypoth'>I  120 </td></tr>
<tr><td>120</td><td>001;0</td><td>334;0</td><td class='hypoth'>A  147 </td><td class='hypoth'>B  120 </td><td class='hypoth'>C  126 </td><td class='hypoth'>D  91 </td><td class='hypoth'>E  119 </td><td class='hypoth'>F  223 </td><td class='hypoth'>G  107 </td><td class='hypoth'>H  223 </td><td class='hypoth'>I  151 </td></tr>
<tr><td>121</td><td>122;5</td><td>005;1</td><td class='hypoth'>A  160 </td><td class='hypoth'>B  121 </td><td class='hypoth'>C  178 </td><td class='hypoth'>D  122 </td><td class='hypoth'>E  38 </td><td class='hypoth'>F  49 </td><td class='hypoth'>G  223 </td><td class='hypoth'>H  174 </td><td class='hypoth'>I  223 </td></tr>
<tr><td>122</td><td>222;5</td><td>000;1</td><td class='hypoth'>A  161 </td><td class='hypoth'>B  122 </td><td class='hypoth'>C  179 </td><td class='hypoth'>D  223 </td><td class='hypoth'>E  123 </td><td class='hypoth'>F  38 </td><td class='hypoth'>G  223 </td><td class='hypoth'>H  121 </td><td class='hypoth'>I  223 </td></tr>
<tr><td>123</td><td>223;5</td><td>001;1</td><td class='hypoth'>A  162 </td><td class='hypoth'>B  123 </td><td class='hypoth'>C  180 </td><td class='hypoth'>D  223 </td><td class='hypoth'>E  154 </td><td class='hypoth'>F  97 </td><td class='hypoth'>G  223 </td><td class='hypoth'>H  38 </td><td class='hypoth'>I  122 </td></tr>
<tr><td>124</td><td>005;1</td><td>122;5</td><td class='hypoth'>A  118 </td><td class='hypoth'>B  124 </td><td class='hypoth'>C  130 </td><td class='hypoth'>D  223 </td><td class='hypoth'>E  223 </td><td class='hypoth'>F  125 </td><td class='hypoth'>G  171 </td><td class='hypoth'>H  42 </td><td class='hypoth'>I  53 </td></tr>
<tr><td>125</td><td>000;1</td><td>222;5</td><td class='hypoth'>A  119 </td><td class='hypoth'>B  125 </td><td class='hypoth'>C  131 </td><td class='hypoth'>D  223 </td><td class='hypoth'>E  223 </td><td class='hypoth'>F  223 </td><td class='hypoth'>G  124 </td><td class='hypoth'>H  126 </td><td class='hypoth'>I  42 </td></tr>
<tr><td>126</td><td>001;1</td><td>223;5</td><td class='hypoth'>A  120 </td><td class='hypoth'>B  126 </td><td class='hypoth'>C  132 </td><td class='hypoth'>D  125 </td><td class='hypoth'>E  223 </td><td class='hypoth'>F  223 </td><td class='hypoth'>G  42 </td><td class='hypoth'>H  157 </td><td class='hypoth'>I  102 </td></tr>
<tr><td>127</td><td>011;4</td><td>005;2</td><td class='hypoth'>A  166 </td><td class='hypoth'>B  127 </td><td class='hypoth'>C  172 </td><td class='hypoth'>D  128 </td><td class='hypoth'>E  50 </td><td class='hypoth'>F  61 </td><td class='hypoth'>G  223 </td><td class='hypoth'>H  141 </td><td class='hypoth'>I  223 </td></tr>
<tr><td>128</td><td>111;4</td><td>000;2</td><td class='hypoth'>A  167 </td><td class='hypoth'>B  128 </td><td class='hypoth'>C  173 </td><td class='hypoth'>D  223 </td><td class='hypoth'>E  129 </td><td class='hypoth'>F  50 </td><td class='hypoth'>G  223 </td><td class='hypoth'>H  127 </td><td class='hypoth'>I  223 </td></tr>
<tr><td>129</td><td>112;4</td><td>001;2</td><td class='hypoth'>A  168 </td><td class='hypoth'>B  129 </td><td class='hypoth'>C  174 </td><td class='hypoth'>D  223 </td><td class='hypoth'>E  160 </td><td class='hypoth'>F  39 </td><td class='hypoth'>G  223 </td><td class='hypoth'>H  50 </td><td class='hypoth'>I  128 </td></tr>
<tr><td>130</td><td>005;2</td><td>011;4</td><td class='hypoth'>A  124 </td><td class='hypoth'>B  130 </td><td class='hypoth'>C  133 </td><td class='hypoth'>D  223 </td><td class='hypoth'>E  131 </td><td class='hypoth'>F  52 </td><td class='hypoth'>G  223 </td><td class='hypoth'>H  63 </td><td class='hypoth'>I  138 </td></tr>
<tr><td>131</td><td>000;2</td><td>111;4</td><td class='hypoth'>A  125 </td><td class='hypoth'>B  131 </td><td class='hypoth'>C  134 </td><td class='hypoth'>D  223 </td><td class='hypoth'>E  223 </td><td class='hypoth'>F  132 </td><td class='hypoth'>G  223 </td><td class='hypoth'>H  52 </td><td class='hypoth'>I  130 </td></tr>
<tr><td>132</td><td>001;2</td><td>112;4</td><td class='hypoth'>A  126 </td><td class='hypoth'>B  132 </td><td class='hypoth'>C  135 </td><td class='hypoth'>D  223 </td><td class='hypoth'>E  223 </td><td class='hypoth'>F  163 </td><td class='hypoth'>G  131 </td><td class='hypoth'>H  41 </td><td class='hypoth'>I  52 </td></tr>
<tr><td>133</td><td>005;3</td><td>005;3</td><td class='hypoth'>A  130 </td><td class='hypoth'>B  133 </td><td class='hypoth'>C  139 </td><td class='hypoth'>D  134 </td><td class='hypoth'>E  62 </td><td class='hypoth'>F  72 </td><td class='hypoth'>G  223 </td><td class='hypoth'>H  114 </td><td class='hypoth'>I  223 </td></tr>
<tr><td>134</td><td>000;3</td><td>000;3</td><td class='hypoth'>A  131 </td><td class='hypoth'>B  134 </td><td class='hypoth'>C  140 </td><td class='hypoth'>D  223 </td><td class='hypoth'>E  135 </td><td class='hypoth'>F  62 </td><td class='hypoth'>G  223 </td><td class='hypoth'>H  133 </td><td class='hypoth'>I  223 </td></tr>
<tr><td>135</td><td>001;3</td><td>001;3</td><td class='hypoth'>A  132 </td><td class='hypoth'>B  135 </td><td class='hypoth'>C  141 </td><td class='hypoth'>D  223 </td><td class='hypoth'>E  166 </td><td class='hypoth'>F  51 </td><td class='hypoth'>G  223 </td><td class='hypoth'>H  62 </td><td class='hypoth'>I  134 </td></tr>
<tr><td>136</td><td>455;2</td><td>005;4</td><td class='hypoth'>A  169 </td><td class='hypoth'>B  136 </td><td class='hypoth'>C  112 </td><td class='hypoth'>D  137 </td><td class='hypoth'>E  73 </td><td class='hypoth'>F  84 </td><td class='hypoth'>G  223 </td><td class='hypoth'>H  222 </td><td class='hypoth'>I  223 </td></tr>
<tr><td>137</td><td>555;2</td><td>000;4</td><td class='hypoth'>A  170 </td><td class='hypoth'>B  137 </td><td class='hypoth'>C  113 </td><td class='hypoth'>D  223 </td><td class='hypoth'>E  138 </td><td class='hypoth'>F  73 </td><td class='hypoth'>G  223 </td><td class='hypoth'>H  136 </td><td class='hypoth'>I  223 </td></tr>
<tr><td>138</td><td>055;2</td><td>001;4</td><td class='hypoth'>A  171 </td><td class='hypoth'>B  138 </td><td class='hypoth'>C  114 </td><td class='hypoth'>D  223 </td><td class='hypoth'>E  130 </td><td class='hypoth'>F  63 </td><td class='hypoth'>G  223 </td><td class='hypoth'>H  73 </td><td class='hypoth'>I  137 </td></tr>
<tr><td>139</td><td>005;4</td><td>455;2</td><td class='hypoth'>A  133 </td><td class='hypoth'>B  139 </td><td class='hypoth'>C  145 </td><td class='hypoth'>D  83 </td><td class='hypoth'>E  94 </td><td class='hypoth'>F  219 </td><td class='hypoth'>G  140 </td><td class='hypoth'>H  223 </td><td class='hypoth'>I  223 </td></tr>
<tr><td>140</td><td>000;4</td><td>555;2</td><td class='hypoth'>A  134 </td><td class='hypoth'>B  140 </td><td class='hypoth'>C  146 </td><td class='hypoth'>D  141 </td><td class='hypoth'>E  83 </td><td class='hypoth'>F  139 </td><td class='hypoth'>G  223 </td><td class='hypoth'>H  223 </td><td class='hypoth'>I  223 </td></tr>
<tr><td>141</td><td>001;4</td><td>055;2</td><td class='hypoth'>A  135 </td><td class='hypoth'>B  141 </td><td class='hypoth'>C  147 </td><td class='hypoth'>D  127 </td><td class='hypoth'>E  61 </td><td class='hypoth'>F  83 </td><td class='hypoth'>G  223 </td><td class='hypoth'>H  140 </td><td class='hypoth'>I  223 </td></tr>
<tr><td>142</td><td>344;1</td><td>005;5</td><td class='hypoth'>A  148 </td><td class='hypoth'>B  142 </td><td class='hypoth'>C  220 </td><td class='hypoth'>D  143 </td><td class='hypoth'>E  85 </td><td class='hypoth'>F  95 </td><td class='hypoth'>G  223 </td><td class='hypoth'>H  204 </td><td class='hypoth'>I  223 </td></tr>
<tr><td>143</td><td>444;1</td><td>000;5</td><td class='hypoth'>A  149 </td><td class='hypoth'>B  143 </td><td class='hypoth'>C  221 </td><td class='hypoth'>D  223 </td><td class='hypoth'>E  144 </td><td class='hypoth'>F  85 </td><td class='hypoth'>G  223 </td><td class='hypoth'>H  142 </td><td class='hypoth'>I  223 </td></tr>
<tr><td>144</td><td>445;1</td><td>001;5</td><td class='hypoth'>A  150 </td><td class='hypoth'>B  144 </td><td class='hypoth'>C  222 </td><td class='hypoth'>D  223 </td><td class='hypoth'>E  169 </td><td class='hypoth'>F  74 </td><td class='hypoth'>G  223 </td><td class='hypoth'>H  85 </td><td class='hypoth'>I  143 </td></tr>
<tr><td>145</td><td>005;5</td><td>344;1</td><td class='hypoth'>A  139 </td><td class='hypoth'>B  145 </td><td class='hypoth'>C  118 </td><td class='hypoth'>D  92 </td><td class='hypoth'>E  201 </td><td class='hypoth'>F  223 </td><td class='hypoth'>G  93 </td><td class='hypoth'>H  223 </td><td class='hypoth'>I  146 </td></tr>
<tr><td>146</td><td>000;5</td><td>444;1</td><td class='hypoth'>A  140 </td><td class='hypoth'>B  146 </td><td class='hypoth'>C  119 </td><td class='hypoth'>D  93 </td><td class='hypoth'>E  145 </td><td class='hypoth'>F  223 </td><td class='hypoth'>G  147 </td><td class='hypoth'>H  223 </td><td class='hypoth'>I  223 </td></tr>
<tr><td>147</td><td>001;5</td><td>445;1</td><td class='hypoth'>A  141 </td><td class='hypoth'>B  147 </td><td class='hypoth'>C  120 </td><td class='hypoth'>D  82 </td><td class='hypoth'>E  93 </td><td class='hypoth'>F  146 </td><td class='hypoth'>G  172 </td><td class='hypoth'>H  223 </td><td class='hypoth'>I  223 </td></tr>
<tr><td>148</td><td>344;0</td><td>011;0</td><td class='hypoth'>A  181 </td><td class='hypoth'>B  148 </td><td class='hypoth'>C  142 </td><td class='hypoth'>D  223 </td><td class='hypoth'>E  149 </td><td class='hypoth'>F  75 </td><td class='hypoth'>G  223 </td><td class='hypoth'>H  86 </td><td class='hypoth'>I  117 </td></tr>
<tr><td>149</td><td>444;0</td><td>111;0</td><td class='hypoth'>A  182 </td><td class='hypoth'>B  149 </td><td class='hypoth'>C  143 </td><td class='hypoth'>D  223 </td><td class='hypoth'>E  223 </td><td class='hypoth'>F  150 </td><td class='hypoth'>G  223 </td><td class='hypoth'>H  75 </td><td class='hypoth'>I  148 </td></tr>
<tr><td>150</td><td>445;0</td><td>112;0</td><td class='hypoth'>A  183 </td><td class='hypoth'>B  150 </td><td class='hypoth'>C  144 </td><td class='hypoth'>D  223 </td><td class='hypoth'>E  223 </td><td class='hypoth'>F  175 </td><td class='hypoth'>G  149 </td><td class='hypoth'>H  76 </td><td class='hypoth'>I  75 </td></tr>
<tr><td>151</td><td>011;0</td><td>344;0</td><td class='hypoth'>A  172 </td><td class='hypoth'>B  151 </td><td class='hypoth'>C  157 </td><td class='hypoth'>D  107 </td><td class='hypoth'>E  120 </td><td class='hypoth'>F  223 </td><td class='hypoth'>G  81 </td><td class='hypoth'>H  223 </td><td class='hypoth'>I  152 </td></tr>
<tr><td>152</td><td>111;0</td><td>444;0</td><td class='hypoth'>A  173 </td><td class='hypoth'>B  152 </td><td class='hypoth'>C  158 </td><td class='hypoth'>D  81 </td><td class='hypoth'>E  151 </td><td class='hypoth'>F  223 </td><td class='hypoth'>G  153 </td><td class='hypoth'>H  223 </td><td class='hypoth'>I  223 </td></tr>
<tr><td>153</td><td>112;0</td><td>445;0</td><td class='hypoth'>A  174 </td><td class='hypoth'>B  153 </td><td class='hypoth'>C  159 </td><td class='hypoth'>D  70 </td><td class='hypoth'>E  81 </td><td class='hypoth'>F  152 </td><td class='hypoth'>G  178 </td><td class='hypoth'>H  223 </td><td class='hypoth'>I  223 </td></tr>
<tr><td>154</td><td>233;5</td><td>011;1</td><td class='hypoth'>A  189 </td><td class='hypoth'>B  154 </td><td class='hypoth'>C  115 </td><td class='hypoth'>D  223 </td><td class='hypoth'>E  155 </td><td class='hypoth'>F  87 </td><td class='hypoth'>G  223 </td><td class='hypoth'>H  97 </td><td class='hypoth'>I  123 </td></tr>
<tr><td>155</td><td>333;5</td><td>111;1</td><td class='hypoth'>A  190 </td><td class='hypoth'>B  155 </td><td class='hypoth'>C  116 </td><td class='hypoth'>D  223 </td><td class='hypoth'>E  223 </td><td class='hypoth'>F  156 </td><td class='hypoth'>G  223 </td><td class='hypoth'>H  87 </td><td class='hypoth'>I  154 </td></tr>
<tr><td>156</td><td>334;5</td><td>112;1</td><td class='hypoth'>A  191 </td><td class='hypoth'>B  156 </td><td class='hypoth'>C  117 </td><td class='hypoth'>D  223 </td><td class='hypoth'>E  223 </td><td class='hypoth'>F  181 </td><td class='hypoth'>G  155 </td><td class='hypoth'>H  88 </td><td class='hypoth'>I  87 </td></tr>
<tr><td>157</td><td>011;1</td><td>233;5</td><td class='hypoth'>A  151 </td><td class='hypoth'>B  157 </td><td class='hypoth'>C  163 </td><td class='hypoth'>D  126 </td><td class='hypoth'>E  223 </td><td class='hypoth'>F  223 </td><td class='hypoth'>G  102 </td><td class='hypoth'>H  158 </td><td class='hypoth'>I  103 </td></tr>
<tr><td>158</td><td>111;1</td><td>333;5</td><td class='hypoth'>A  152 </td><td class='hypoth'>B  158 </td><td class='hypoth'>C  164 </td><td class='hypoth'>D  157 </td><td class='hypoth'>E  223 </td><td class='hypoth'>F  223 </td><td class='hypoth'>G  103 </td><td class='hypoth'>H  223 </td><td class='hypoth'>I  159 </td></tr>
<tr><td>159</td><td>112;1</td><td>334;5</td><td class='hypoth'>A  153 </td><td class='hypoth'>B  159 </td><td class='hypoth'>C  165 </td><td class='hypoth'>D  103 </td><td class='hypoth'>E  158 </td><td class='hypoth'>F  223 </td><td class='hypoth'>G  80 </td><td class='hypoth'>H  223 </td><td class='hypoth'>I  184 </td></tr>
<tr><td>160</td><td>122;4</td><td>011;2</td><td class='hypoth'>A  195 </td><td class='hypoth'>B  160 </td><td class='hypoth'>C  121 </td><td class='hypoth'>D  223 </td><td class='hypoth'>E  161 </td><td class='hypoth'>F  98 </td><td class='hypoth'>G  223 </td><td class='hypoth'>H  39 </td><td class='hypoth'>I  129 </td></tr>
<tr><td>161</td><td>222;4</td><td>111;2</td><td class='hypoth'>A  196 </td><td class='hypoth'>B  161 </td><td class='hypoth'>C  122 </td><td class='hypoth'>D  223 </td><td class='hypoth'>E  223 </td><td class='hypoth'>F  162 </td><td class='hypoth'>G  223 </td><td class='hypoth'>H  98 </td><td class='hypoth'>I  160 </td></tr>
<tr><td>162</td><td>223;4</td><td>112;2</td><td class='hypoth'>A  197 </td><td class='hypoth'>B  162 </td><td class='hypoth'>C  123 </td><td class='hypoth'>D  223 </td><td class='hypoth'>E  223 </td><td class='hypoth'>F  189 </td><td class='hypoth'>G  161 </td><td class='hypoth'>H  99 </td><td class='hypoth'>I  98 </td></tr>
<tr><td>163</td><td>011;2</td><td>122;4</td><td class='hypoth'>A  157 </td><td class='hypoth'>B  163 </td><td class='hypoth'>C  166 </td><td class='hypoth'>D  223 </td><td class='hypoth'>E  223 </td><td class='hypoth'>F  164 </td><td class='hypoth'>G  132 </td><td class='hypoth'>H  100 </td><td class='hypoth'>I  41 </td></tr>
<tr><td>164</td><td>111;2</td><td>222;4</td><td class='hypoth'>A  158 </td><td class='hypoth'>B  164 </td><td class='hypoth'>C  167 </td><td class='hypoth'>D  223 </td><td class='hypoth'>E  223 </td><td class='hypoth'>F  223 </td><td class='hypoth'>G  163 </td><td class='hypoth'>H  165 </td><td class='hypoth'>I  100 </td></tr>
<tr><td>165</td><td>112;2</td><td>223;4</td><td class='hypoth'>A  159 </td><td class='hypoth'>B  165 </td><td class='hypoth'>C  168 </td><td class='hypoth'>D  164 </td><td class='hypoth'>E  223 </td><td class='hypoth'>F  223 </td><td class='hypoth'>G  100 </td><td class='hypoth'>H  192 </td><td class='hypoth'>I  90 </td></tr>
<tr><td>166</td><td>011;3</td><td>011;3</td><td class='hypoth'>A  163 </td><td class='hypoth'>B  166 </td><td class='hypoth'>C  127 </td><td class='hypoth'>D  223 </td><td class='hypoth'>E  167 </td><td class='hypoth'>F  40 </td><td class='hypoth'>G  223 </td><td class='hypoth'>H  51 </td><td class='hypoth'>I  135 </td></tr>
<tr><td>167</td><td>111;3</td><td>111;3</td><td class='hypoth'>A  164 </td><td class='hypoth'>B  167 </td><td class='hypoth'>C  128 </td><td class='hypoth'>D  223 </td><td class='hypoth'>E  223 </td><td class='hypoth'>F  168 </td><td class='hypoth'>G  223 </td><td class='hypoth'>H  40 </td><td class='hypoth'>I  166 </td></tr>
<tr><td>168</td><td>112;3</td><td>112;3</td><td class='hypoth'>A  165 </td><td class='hypoth'>B  168 </td><td class='hypoth'>C  129 </td><td class='hypoth'>D  223 </td><td class='hypoth'>E  223 </td><td class='hypoth'>F  195 </td><td class='hypoth'>G  167 </td><td class='hypoth'>H  101 </td><td class='hypoth'>I  40 </td></tr>
<tr><td>169</td><td>455;1</td><td>011;5</td><td class='hypoth'>A  175 </td><td class='hypoth'>B  169 </td><td class='hypoth'>C  136 </td><td class='hypoth'>D  223 </td><td class='hypoth'>E  170 </td><td class='hypoth'>F  64 </td><td class='hypoth'>G  223 </td><td class='hypoth'>H  74 </td><td class='hypoth'>I  144 </td></tr>
<tr><td>170</td><td>555;1</td><td>111;5</td><td class='hypoth'>A  176 </td><td class='hypoth'>B  170 </td><td class='hypoth'>C  137 </td><td class='hypoth'>D  223 </td><td class='hypoth'>E  223 </td><td class='hypoth'>F  171 </td><td class='hypoth'>G  223 </td><td class='hypoth'>H  64 </td><td class='hypoth'>I  169 </td></tr>
<tr><td>171</td><td>055;1</td><td>112;5</td><td class='hypoth'>A  177 </td><td class='hypoth'>B  171 </td><td class='hypoth'>C  138 </td><td class='hypoth'>D  223 </td><td class='hypoth'>E  223 </td><td class='hypoth'>F  124 </td><td class='hypoth'>G  170 </td><td class='hypoth'>H  53 </td><td class='hypoth'>I  64 </td></tr>
<tr><td>172</td><td>011;5</td><td>455;1</td><td class='hypoth'>A  127 </td><td class='hypoth'>B  172 </td><td class='hypoth'>C  151 </td><td class='hypoth'>D  71 </td><td class='hypoth'>E  82 </td><td class='hypoth'>F  147 </td><td class='hypoth'>G  173 </td><td class='hypoth'>H  223 </td><td class='hypoth'>I  223 </td></tr>
<tr><td>173</td><td>111;5</td><td>555;1</td><td class='hypoth'>A  128 </td><td class='hypoth'>B  173 </td><td class='hypoth'>C  152 </td><td class='hypoth'>D  174 </td><td class='hypoth'>E  71 </td><td class='hypoth'>F  172 </td><td class='hypoth'>G  223 </td><td class='hypoth'>H  223 </td><td class='hypoth'>I  223 </td></tr>
<tr><td>174</td><td>112;5</td><td>055;1</td><td class='hypoth'>A  129 </td><td class='hypoth'>B  174 </td><td class='hypoth'>C  153 </td><td class='hypoth'>D  121 </td><td class='hypoth'>E  49 </td><td class='hypoth'>F  71 </td><td class='hypoth'>G  223 </td><td class='hypoth'>H  173 </td><td class='hypoth'>I  223 </td></tr>
<tr><td>175</td><td>455;0</td><td>122;0</td><td class='hypoth'>A  199 </td><td class='hypoth'>B  175 </td><td class='hypoth'>C  169 </td><td class='hypoth'>D  223 </td><td class='hypoth'>E  223 </td><td class='hypoth'>F  176 </td><td class='hypoth'>G  150 </td><td class='hypoth'>H  54 </td><td class='hypoth'>I  76 </td></tr>
<tr><td>176</td><td>555;0</td><td>222;0</td><td class='hypoth'>A  200 </td><td class='hypoth'>B  176 </td><td class='hypoth'>C  170 </td><td class='hypoth'>D  223 </td><td class='hypoth'>E  223 </td><td class='hypoth'>F  223 </td><td class='hypoth'>G  175 </td><td class='hypoth'>H  177 </td><td class='hypoth'>I  54 </td></tr>
<tr><td>177</td><td>055;0</td><td>223;0</td><td class='hypoth'>A  201 </td><td class='hypoth'>B  177 </td><td class='hypoth'>C  171 </td><td class='hypoth'>D  176 </td><td class='hypoth'>E  223 </td><td class='hypoth'>F  223 </td><td class='hypoth'>G  54 </td><td class='hypoth'>H  118 </td><td class='hypoth'>I  43 </td></tr>
<tr><td>178</td><td>122;0</td><td>455;0</td><td class='hypoth'>A  121 </td><td class='hypoth'>B  178 </td><td class='hypoth'>C  184 </td><td class='hypoth'>D  60 </td><td class='hypoth'>E  70 </td><td class='hypoth'>F  153 </td><td class='hypoth'>G  179 </td><td class='hypoth'>H  223 </td><td class='hypoth'>I  223 </td></tr>
<tr><td>179</td><td>222;0</td><td>555;0</td><td class='hypoth'>A  122 </td><td class='hypoth'>B  179 </td><td class='hypoth'>C  185 </td><td class='hypoth'>D  180 </td><td class='hypoth'>E  60 </td><td class='hypoth'>F  178 </td><td class='hypoth'>G  223 </td><td class='hypoth'>H  223 </td><td class='hypoth'>I  223 </td></tr>
<tr><td>180</td><td>223;0</td><td>055;0</td><td class='hypoth'>A  123 </td><td class='hypoth'>B  180 </td><td class='hypoth'>C  186 </td><td class='hypoth'>D  115 </td><td class='hypoth'>E  37 </td><td class='hypoth'>F  60 </td><td class='hypoth'>G  223 </td><td class='hypoth'>H  179 </td><td class='hypoth'>I  223 </td></tr>
<tr><td>181</td><td>344;5</td><td>122;1</td><td class='hypoth'>A  206 </td><td class='hypoth'>B  181 </td><td class='hypoth'>C  148 </td><td class='hypoth'>D  223 </td><td class='hypoth'>E  223 </td><td class='hypoth'>F  182 </td><td class='hypoth'>G  156 </td><td class='hypoth'>H  65 </td><td class='hypoth'>I  88 </td></tr>
<tr><td>182</td><td>444;5</td><td>222;1</td><td class='hypoth'>A  207 </td><td class='hypoth'>B  182 </td><td class='hypoth'>C  149 </td><td class='hypoth'>D  223 </td><td class='hypoth'>E  223 </td><td class='hypoth'>F  223 </td><td class='hypoth'>G  181 </td><td class='hypoth'>H  183 </td><td class='hypoth'>I  65 </td></tr>
<tr><td>183</td><td>445;5</td><td>223;1</td><td class='hypoth'>A  208 </td><td class='hypoth'>B  183 </td><td class='hypoth'>C  150 </td><td class='hypoth'>D  182 </td><td class='hypoth'>E  223 </td><td class='hypoth'>F  223 </td><td class='hypoth'>G  65 </td><td class='hypoth'>H  199 </td><td class='hypoth'>I  55 </td></tr>
<tr><td>184</td><td>122;1</td><td>344;5</td><td class='hypoth'>A  178 </td><td class='hypoth'>B  184 </td><td class='hypoth'>C  192 </td><td class='hypoth'>D  80 </td><td class='hypoth'>E  159 </td><td class='hypoth'>F  223 </td><td class='hypoth'>G  69 </td><td class='hypoth'>H  223 </td><td class='hypoth'>I  185 </td></tr>
<tr><td>185</td><td>222;1</td><td>444;5</td><td class='hypoth'>A  179 </td><td class='hypoth'>B  185 </td><td class='hypoth'>C  193 </td><td class='hypoth'>D  69 </td><td class='hypoth'>E  184 </td><td class='hypoth'>F  223 </td><td class='hypoth'>G  186 </td><td class='hypoth'>H  223 </td><td class='hypoth'>I  223 </td></tr>
<tr><td>186</td><td>223;1</td><td>445;5</td><td class='hypoth'>A  180 </td><td class='hypoth'>B  186 </td><td class='hypoth'>C  194 </td><td class='hypoth'>D  59 </td><td class='hypoth'>E  69 </td><td class='hypoth'>F  185 </td><td class='hypoth'>G  202 </td><td class='hypoth'>H  223 </td><td class='hypoth'>I  223 </td></tr>
<tr><td>187</td><td>;0</td><td>;0</td><td class='certain'>A  205 </td><td class='certain'>B  187 </td><td class='certain'>C  198 </td><td class='certain'>D  3 </td><td class='certain'>E  15 </td><td class='certain'>F  16 </td><td class='certain'>G  2 </td><td class='certain'>H  17 </td><td class='certain'>I  1 </td></tr>
<tr><td>188</td><td>;3</td><td>;3</td><td class='certain'>A  209 </td><td class='certain'>B  188 </td><td class='certain'>C  213 </td><td class='certain'>D  21 </td><td class='certain'>E  4 </td><td class='certain'>F  5 </td><td class='certain'>G  20 </td><td class='certain'>H  6 </td><td class='certain'>I  19 </td></tr>
<tr><td>189</td><td>233;4</td><td>122;2</td><td class='hypoth'>A  214 </td><td class='hypoth'>B  189 </td><td class='hypoth'>C  154 </td><td class='hypoth'>D  223 </td><td class='hypoth'>E  223 </td><td class='hypoth'>F  190 </td><td class='hypoth'>G  162 </td><td class='hypoth'>H  77 </td><td class='hypoth'>I  99 </td></tr>
<tr><td>190</td><td>333;4</td><td>222;2</td><td class='hypoth'>A  215 </td><td class='hypoth'>B  190 </td><td class='hypoth'>C  155 </td><td class='hypoth'>D  223 </td><td class='hypoth'>E  223 </td><td class='hypoth'>F  223 </td><td class='hypoth'>G  189 </td><td class='hypoth'>H  191 </td><td class='hypoth'>I  77 </td></tr>
<tr><td>191</td><td>334;4</td><td>223;2</td><td class='hypoth'>A  216 </td><td class='hypoth'>B  191 </td><td class='hypoth'>C  156 </td><td class='hypoth'>D  190 </td><td class='hypoth'>E  223 </td><td class='hypoth'>F  223 </td><td class='hypoth'>G  77 </td><td class='hypoth'>H  206 </td><td class='hypoth'>I  66 </td></tr>
<tr><td>192</td><td>122;2</td><td>233;4</td><td class='hypoth'>A  184 </td><td class='hypoth'>B  192 </td><td class='hypoth'>C  195 </td><td class='hypoth'>D  165 </td><td class='hypoth'>E  223 </td><td class='hypoth'>F  223 </td><td class='hypoth'>G  90 </td><td class='hypoth'>H  193 </td><td class='hypoth'>I  79 </td></tr>
<tr><td>193</td><td>222;2</td><td>333;4</td><td class='hypoth'>A  185 </td><td class='hypoth'>B  193 </td><td class='hypoth'>C  196 </td><td class='hypoth'>D  192 </td><td class='hypoth'>E  223 </td><td class='hypoth'>F  223 </td><td class='hypoth'>G  79 </td><td class='hypoth'>H  223 </td><td class='hypoth'>I  194 </td></tr>
<tr><td>194</td><td>223;2</td><td>334;4</td><td class='hypoth'>A  186 </td><td class='hypoth'>B  194 </td><td class='hypoth'>C  197 </td><td class='hypoth'>D  79 </td><td class='hypoth'>E  193 </td><td class='hypoth'>F  223 </td><td class='hypoth'>G  68 </td><td class='hypoth'>H  223 </td><td class='hypoth'>I  210 </td></tr>
<tr><td>195</td><td>122;3</td><td>122;3</td><td class='hypoth'>A  192 </td><td class='hypoth'>B  195 </td><td class='hypoth'>C  160 </td><td class='hypoth'>D  223 </td><td class='hypoth'>E  223 </td><td class='hypoth'>F  196 </td><td class='hypoth'>G  168 </td><td class='hypoth'>H  89 </td><td class='hypoth'>I  101 </td></tr>
<tr><td>196</td><td>222;3</td><td>222;3</td><td class='hypoth'>A  193 </td><td class='hypoth'>B  196 </td><td class='hypoth'>C  161 </td><td class='hypoth'>D  223 </td><td class='hypoth'>E  223 </td><td class='hypoth'>F  223 </td><td class='hypoth'>G  195 </td><td class='hypoth'>H  197 </td><td class='hypoth'>I  89 </td></tr>
<tr><td>197</td><td>223;3</td><td>223;3</td><td class='hypoth'>A  194 </td><td class='hypoth'>B  197 </td><td class='hypoth'>C  162 </td><td class='hypoth'>D  196 </td><td class='hypoth'>E  223 </td><td class='hypoth'>F  223 </td><td class='hypoth'>G  89 </td><td class='hypoth'>H  214 </td><td class='hypoth'>I  78 </td></tr>
<tr><td>198</td><td>;1</td><td>;5</td><td class='certain'>A  187 </td><td class='certain'>B  198 </td><td class='certain'>C  209 </td><td class='certain'>D  35 </td><td class='certain'>E  10 </td><td class='certain'>F  11 </td><td class='certain'>G  36 </td><td class='certain'>H  12 </td><td class='certain'>I  31 </td></tr>
<tr><td>199</td><td>455;5</td><td>233;1</td><td class='hypoth'>A  217 </td><td class='hypoth'>B  199 </td><td class='hypoth'>C  175 </td><td class='hypoth'>D  183 </td><td class='hypoth'>E  223 </td><td class='hypoth'>F  223 </td><td class='hypoth'>G  55 </td><td class='hypoth'>H  200 </td><td class='hypoth'>I  44 </td></tr>
<tr><td>200</td><td>555;5</td><td>333;1</td><td class='hypoth'>A  218 </td><td class='hypoth'>B  200 </td><td class='hypoth'>C  176 </td><td class='hypoth'>D  199 </td><td class='hypoth'>E  223 </td><td class='hypoth'>F  223 </td><td class='hypoth'>G  44 </td><td class='hypoth'>H  223 </td><td class='hypoth'>I  201 </td></tr>
<tr><td>201</td><td>055;5</td><td>334;1</td><td class='hypoth'>A  219 </td><td class='hypoth'>B  201 </td><td class='hypoth'>C  177 </td><td class='hypoth'>D  44 </td><td class='hypoth'>E  200 </td><td class='hypoth'>F  223 </td><td class='hypoth'>G  92 </td><td class='hypoth'>H  223 </td><td class='hypoth'>I  145 </td></tr>
<tr><td>202</td><td>233;1</td><td>455;5</td><td class='hypoth'>A  115 </td><td class='hypoth'>B  202 </td><td class='hypoth'>C  210 </td><td class='hypoth'>D  48 </td><td class='hypoth'>E  59 </td><td class='hypoth'>F  186 </td><td class='hypoth'>G  203 </td><td class='hypoth'>H  223 </td><td class='hypoth'>I  223 </td></tr>
<tr><td>203</td><td>333;1</td><td>555;5</td><td class='hypoth'>A  116 </td><td class='hypoth'>B  203 </td><td class='hypoth'>C  211 </td><td class='hypoth'>D  204 </td><td class='hypoth'>E  48 </td><td class='hypoth'>F  202 </td><td class='hypoth'>G  223 </td><td class='hypoth'>H  223 </td><td class='hypoth'>I  223 </td></tr>
<tr><td>204</td><td>334;1</td><td>055;5</td><td class='hypoth'>A  117 </td><td class='hypoth'>B  204 </td><td class='hypoth'>C  212 </td><td class='hypoth'>D  142 </td><td class='hypoth'>E  95 </td><td class='hypoth'>F  48 </td><td class='hypoth'>G  223 </td><td class='hypoth'>H  203 </td><td class='hypoth'>I  223 </td></tr>
<tr><td>205</td><td>;5</td><td>;1</td><td class='certain'>A  213 </td><td class='certain'>B  205 </td><td class='certain'>C  187 </td><td class='certain'>D  9 </td><td class='certain'>E  22 </td><td class='certain'>F  23 </td><td class='certain'>G  8 </td><td class='certain'>H  24 </td><td class='certain'>I  7 </td></tr>
<tr><td>206</td><td>344;4</td><td>233;2</td><td class='hypoth'>A  109 </td><td class='hypoth'>B  206 </td><td class='hypoth'>C  181 </td><td class='hypoth'>D  191 </td><td class='hypoth'>E  223 </td><td class='hypoth'>F  223 </td><td class='hypoth'>G  66 </td><td class='hypoth'>H  207 </td><td class='hypoth'>I  56 </td></tr>
<tr><td>207</td><td>444;4</td><td>333;2</td><td class='hypoth'>A  110 </td><td class='hypoth'>B  207 </td><td class='hypoth'>C  182 </td><td class='hypoth'>D  206 </td><td class='hypoth'>E  223 </td><td class='hypoth'>F  223 </td><td class='hypoth'>G  56 </td><td class='hypoth'>H  223 </td><td class='hypoth'>I  208 </td></tr>
<tr><td>208</td><td>445;4</td><td>334;2</td><td class='hypoth'>A  111 </td><td class='hypoth'>B  208 </td><td class='hypoth'>C  183 </td><td class='hypoth'>D  56 </td><td class='hypoth'>E  207 </td><td class='hypoth'>F  223 </td><td class='hypoth'>G  45 </td><td class='hypoth'>H  223 </td><td class='hypoth'>I  217 </td></tr>
<tr><td>209</td><td>;2</td><td>;4</td><td class='certain'>A  198 </td><td class='certain'>B  209 </td><td class='certain'>C  188 </td><td class='certain'>D  27 </td><td class='certain'>E  34 </td><td class='certain'>F  33 </td><td class='certain'>G  26 </td><td class='certain'>H  32 </td><td class='certain'>I  25 </td></tr>
<tr><td>210</td><td>233;2</td><td>344;4</td><td class='hypoth'>A  202 </td><td class='hypoth'>B  210 </td><td class='hypoth'>C  214 </td><td class='hypoth'>D  68 </td><td class='hypoth'>E  194 </td><td class='hypoth'>F  223 </td><td class='hypoth'>G  58 </td><td class='hypoth'>H  223 </td><td class='hypoth'>I  211 </td></tr>
<tr><td>211</td><td>333;2</td><td>444;4</td><td class='hypoth'>A  203 </td><td class='hypoth'>B  211 </td><td class='hypoth'>C  215 </td><td class='hypoth'>D  58 </td><td class='hypoth'>E  210 </td><td class='hypoth'>F  223 </td><td class='hypoth'>G  212 </td><td class='hypoth'>H  223 </td><td class='hypoth'>I  223 </td></tr>
<tr><td>212</td><td>334;2</td><td>445;4</td><td class='hypoth'>A  204 </td><td class='hypoth'>B  212 </td><td class='hypoth'>C  216 </td><td class='hypoth'>D  47 </td><td class='hypoth'>E  58 </td><td class='hypoth'>F  211 </td><td class='hypoth'>G  220 </td><td class='hypoth'>H  223 </td><td class='hypoth'>I  223 </td></tr>
<tr><td>213</td><td>;4</td><td>;2</td><td class='certain'>A  188 </td><td class='certain'>B  213 </td><td class='certain'>C  205 </td><td class='certain'>D  14 </td><td class='certain'>E  28 </td><td class='certain'>F  29 </td><td class='certain'>G  13 </td><td class='certain'>H  30 </td><td class='certain'>I  18 </td></tr>
<tr><td>214</td><td>233;3</td><td>233;3</td><td class='hypoth'>A  210 </td><td class='hypoth'>B  214 </td><td class='hypoth'>C  189 </td><td class='hypoth'>D  197 </td><td class='hypoth'>E  223 </td><td class='hypoth'>F  223 </td><td class='hypoth'>G  78 </td><td class='hypoth'>H  215 </td><td class='hypoth'>I  67 </td></tr>
<tr><td>215</td><td>333;3</td><td>333;3</td><td class='hypoth'>A  211 </td><td class='hypoth'>B  215 </td><td class='hypoth'>C  190 </td><td class='hypoth'>D  214 </td><td class='hypoth'>E  223 </td><td class='hypoth'>F  223 </td><td class='hypoth'>G  67 </td><td class='hypoth'>H  223 </td><td class='hypoth'>I  216 </td></tr>
<tr><td>216</td><td>334;3</td><td>334;3</td><td class='hypoth'>A  212 </td><td class='hypoth'>B  216 </td><td class='hypoth'>C  191 </td><td class='hypoth'>D  67 </td><td class='hypoth'>E  215 </td><td class='hypoth'>F  223 </td><td class='hypoth'>G  57 </td><td class='hypoth'>H  223 </td><td class='hypoth'>I  109 </td></tr>
<tr><td>217</td><td>455;4</td><td>344;2</td><td class='hypoth'>A  112 </td><td class='hypoth'>B  217 </td><td class='hypoth'>C  199 </td><td class='hypoth'>D  45 </td><td class='hypoth'>E  208 </td><td class='hypoth'>F  223 </td><td class='hypoth'>G  104 </td><td class='hypoth'>H  223 </td><td class='hypoth'>I  218 </td></tr>
<tr><td>218</td><td>555;4</td><td>444;2</td><td class='hypoth'>A  113 </td><td class='hypoth'>B  218 </td><td class='hypoth'>C  200 </td><td class='hypoth'>D  104 </td><td class='hypoth'>E  217 </td><td class='hypoth'>F  223 </td><td class='hypoth'>G  219 </td><td class='hypoth'>H  223 </td><td class='hypoth'>I  223 </td></tr>
<tr><td>219</td><td>055;4</td><td>445;2</td><td class='hypoth'>A  114 </td><td class='hypoth'>B  219 </td><td class='hypoth'>C  201 </td><td class='hypoth'>D  94 </td><td class='hypoth'>E  104 </td><td class='hypoth'>F  218 </td><td class='hypoth'>G  139 </td><td class='hypoth'>H  223 </td><td class='hypoth'>I  223 </td></tr>
<tr><td>220</td><td>344;2</td><td>455;4</td><td class='hypoth'>A  142 </td><td class='hypoth'>B  220 </td><td class='hypoth'>C  109 </td><td class='hypoth'>D  108 </td><td class='hypoth'>E  47 </td><td class='hypoth'>F  212 </td><td class='hypoth'>G  221 </td><td class='hypoth'>H  223 </td><td class='hypoth'>I  223 </td></tr>
<tr><td>221</td><td>444;2</td><td>555;4</td><td class='hypoth'>A  143 </td><td class='hypoth'>B  221 </td><td class='hypoth'>C  110 </td><td class='hypoth'>D  222 </td><td class='hypoth'>E  108 </td><td class='hypoth'>F  220 </td><td class='hypoth'>G  223 </td><td class='hypoth'>H  223 </td><td class='hypoth'>I  223 </td></tr>
<tr><td>222</td><td>445;2</td><td>055;4</td><td class='hypoth'>A  144 </td><td class='hypoth'>B  222 </td><td class='hypoth'>C  111 </td><td class='hypoth'>D  136 </td><td class='hypoth'>E  84 </td><td class='hypoth'>F  108 </td><td class='hypoth'>G  223 </td><td class='hypoth'>H  221 </td><td class='hypoth'>I  223 </td></tr>
<tr><td>223</td></tr>
</table>
<pre>
.                                -------
.                               /  <span class='hypoth'>119</span>  \
.                              /<span class='hypoth'>146</span>   <span class='hypoth'>125</span>\
.                       -------           -------
.                      /  <span class='hypoth'>118</span>  \<span class='hypoth'>140</span>   <span class='hypoth'>131</span>/  <span class='hypoth'>120</span>  \
.                     /<span class='hypoth'>145</span>   <span class='hypoth'>124</span>\  <span class='hypoth'>134</span>  /<span class='hypoth'>147</span>   <span class='hypoth'>126</span>\
.              -------           -------           -------
.             /  <span class='hypoth'>177</span>  \<span class='hypoth'>139</span>   <span class='hypoth'>130</span>/  <span class='certain'> 91</span>  \<span class='hypoth'>141</span>   <span class='hypoth'>132</span>/  <span class='hypoth'>151</span>  \
.            /<span class='hypoth'>201</span>   <span class='hypoth'>171</span>\  <span class='hypoth'>133</span>  /<span class='certain'> 93</span>   <span class='certain'> 42</span>\  <span class='hypoth'>135</span>  /<span class='hypoth'>172</span>   <span class='hypoth'>157</span>\
.     -------           -------           -------           -------
.    /  <span class='hypoth'>176</span>  \<span class='hypoth'>219</span>   <span class='hypoth'>138</span>/  <span class='hypoth'> 43</span>  \<span class='certain'> 83</span>   <span class='certain'> 52</span>/  <span class='hypoth'>107</span>  \<span class='hypoth'>127</span>   <span class='hypoth'>163</span>/  <span class='hypoth'>152</span>  \
.   /<span class='hypoth'>200</span>   <span class='hypoth'>170</span>\  <span class='hypoth'>114</span>  /<span class='hypoth'> 92</span>   <span class='hypoth'> 53</span>\  <span class='certain'> 62</span>  /<span class='hypoth'> 82</span>   <span class='hypoth'>102</span>\  <span class='hypoth'>166</span>  /<span class='hypoth'>173</span>   <span class='hypoth'>158</span>\
.  (           -------           -------           -------           )
.   \<span class='hypoth'>218</span>   <span class='hypoth'>137</span>/  <span class='certain'> 54</span>  \<span class='hypoth'> 94</span>   <span class='hypoth'> 63</span>/  <span class='certain'> 16</span>  \<span class='hypoth'> 61</span>   <span class='hypoth'> 41</span>/  <span class='certain'> 81</span>  \<span class='hypoth'>128</span>   <span class='hypoth'>164</span>/
.    \  <span class='hypoth'>113</span>  /<span class='certain'> 44</span>   <span class='certain'> 64</span>\  <span class='hypoth'> 72</span>  /<span class='hypoth'> 24</span>   <span class='hypoth'> 10</span>\  <span class='hypoth'> 51</span>  /<span class='certain'> 71</span>   <span class='certain'>103</span>\  <span class='hypoth'>167</span>  /
.     -------           -------           -------           -------
.    /  <span class='hypoth'>175</span>  \<span class='certain'>104</span>   <span class='certain'> 73</span>/  <span class='hypoth'> 15</span>  \<span class='hypoth'> 18</span>   <span class='hypoth'> 27</span>/  <span class='hypoth'> 17</span>  \<span class='certain'> 50</span>   <span class='certain'>100</span>/  <span class='hypoth'>153</span>  \
.   /<span class='hypoth'>199</span>   <span class='hypoth'>169</span>\  <span class='certain'>106</span>  /<span class='certain'> 23</span>   <span class='hypoth'> 35</span>\  <span class='hypoth'> 20</span>  /<span class='hypoth'> 7 </span>   <span class='certain'> 11</span>\  <span class='certain'> 40</span>  /<span class='hypoth'>174</span>   <span class='hypoth'>159</span>\
.  (           -------           -------           -------           )
.   \<span class='hypoth'>217</span>   <span class='hypoth'>136</span>/  <span class='hypoth'> 76</span>  \<span class='hypoth'> 30</span>   <span class='hypoth'> 26</span>/  <span class='certain'>187</span>  \<span class='hypoth'> 13</span>   <span class='hypoth'> 34</span>/  <span class='hypoth'> 70</span>  \<span class='hypoth'>129</span>   <span class='hypoth'>165</span>/
.    \  <span class='hypoth'>112</span>  /<span class='hypoth'> 55</span>   <span class='hypoth'> 74</span>\  <span class='hypoth'> 19</span>  /<span class='certain'>205</span>   <span class='certain'>198</span>\  <span class='hypoth'> 21</span>  /<span class='hypoth'> 49</span>   <span class='hypoth'> 80</span>\  <span class='hypoth'>168</span>  /
.     -------           -------           -------           -------
.    /  <span class='hypoth'>150</span>  \<span class='hypoth'> 45</span>   <span class='hypoth'> 84</span>/  <span class='hypoth'> 3 </span>  \<span class='certain'>213</span>   <span class='certain'>209</span>/  <span class='hypoth'> 1 </span>  \<span class='hypoth'> 39</span>   <span class='hypoth'> 90</span>/  <span class='hypoth'>178</span>  \
.   /<span class='hypoth'>183</span>   <span class='hypoth'>144</span>\  <span class='hypoth'>105</span>  /<span class='hypoth'> 22</span>   <span class='hypoth'> 36</span>\  <span class='certain'>188</span>  /<span class='hypoth'> 8 </span>   <span class='hypoth'> 12</span>\  <span class='hypoth'>101</span>  /<span class='hypoth'>121</span>   <span class='hypoth'>184</span>\
.  (           -------           -------           -------           )
.   \<span class='hypoth'>208</span>   <span class='hypoth'>222</span>/  <span class='certain'> 75</span>  \<span class='certain'> 29</span>   <span class='hypoth'> 25</span>/  <span class='hypoth'> 2 </span>  \<span class='hypoth'> 14</span>   <span class='certain'> 33</span>/  <span class='certain'> 60</span>  \<span class='hypoth'>160</span>   <span class='hypoth'>192</span>/
.    \  <span class='hypoth'>111</span>  /<span class='certain'> 65</span>   <span class='certain'> 85</span>\  <span class='hypoth'> 6 </span>  /<span class='hypoth'> 9 </span>   <span class='hypoth'> 31</span>\  <span class='hypoth'> 4 </span>  /<span class='certain'> 38</span>   <span class='certain'> 69</span>\  <span class='hypoth'>195</span>  /
.     -------           -------           -------           -------
.    /  <span class='hypoth'>149</span>  \<span class='certain'> 56</span>   <span class='certain'>108</span>/  <span class='hypoth'> 86</span>  \<span class='hypoth'> 28</span>   <span class='hypoth'> 32</span>/  <span class='hypoth'> 37</span>  \<span class='certain'> 98</span>   <span class='certain'> 79</span>/  <span class='hypoth'>179</span>  \
.   /<span class='hypoth'>182</span>   <span class='hypoth'>143</span>\  <span class='certain'> 46</span>  /<span class='hypoth'> 88</span>   <span class='hypoth'> 95</span>\  <span class='certain'> 5 </span>  /<span class='hypoth'> 97</span>   <span class='hypoth'> 59</span>\  <span class='certain'> 89</span>  /<span class='hypoth'>122</span>   <span class='hypoth'>185</span>\
.  (           -------           -------           -------           )
.   \<span class='hypoth'>207</span>   <span class='hypoth'>221</span>/  <span class='hypoth'>148</span>  \<span class='hypoth'> 66</span>   <span class='hypoth'> 47</span>/  <span class='certain'> 96</span>  \<span class='hypoth'> 99</span>   <span class='hypoth'> 68</span>/  <span class='hypoth'>180</span>  \<span class='hypoth'>161</span>   <span class='hypoth'>193</span>/
.    \  <span class='hypoth'>110</span>  /<span class='hypoth'>181</span>   <span class='hypoth'>142</span>\  <span class='hypoth'> 57</span>  /<span class='certain'> 87</span>   <span class='certain'> 48</span>\  <span class='hypoth'> 78</span>  /<span class='hypoth'>123</span>   <span class='hypoth'>186</span>\  <span class='hypoth'>196</span>  /
.     -------           -------           -------           -------
.            \<span class='hypoth'>206</span>   <span class='hypoth'>220</span>/  <span class='hypoth'>117</span>  \<span class='certain'> 77</span>   <span class='certain'> 58</span>/  <span class='hypoth'>115</span>  \<span class='hypoth'>162</span>   <span class='hypoth'>194</span>/
.             \  <span class='hypoth'>109</span>  /<span class='hypoth'>156</span>   <span class='hypoth'>204</span>\  <span class='certain'> 67</span>  /<span class='hypoth'>154</span>   <span class='hypoth'>202</span>\  <span class='hypoth'>197</span>  /
.              -------           -------           -------
.                     \<span class='hypoth'>191</span>   <span class='hypoth'>212</span>/  <span class='hypoth'>116</span>  \<span class='hypoth'>189</span>   <span class='hypoth'>210</span>/
.                      \  <span class='hypoth'>216</span>  /<span class='hypoth'>155</span>   <span class='hypoth'>203</span>\  <span class='hypoth'>214</span>  /
.                       -------           -------
.                              \<span class='hypoth'>190</span>   <span class='hypoth'>211</span>/
.                               \  <span class='hypoth'>215</span>  /
.                                -------

</pre>

=end html
