#!/bin/sh
# -*- encoding: utf-8; indent-tabs-mode: nil -*-
#
#
#     Programme affichant la cartographie partielle de l'As des As en HTML
#     Program displaying the partial map of Ace of Aces as an HTML file
#     Copyright (C) 2018 Jean Forget
#
#     Voir la licence dans la documentation incluse ci-dessous.
#     See the license in the embedded documentation below.
#

if [ 1 -ne 0 ]
then
  perl6 init.p6
  perl6 aff.p6 > etape0.html
  perl6 maj.p6 --page=187 -a=205 -b=187 -c=198 -d=3   -e=15  -f=16 -g=2   -h=17  -i=1
  perl6 maj.p6 --page=16  -a=24  -b=16  -c=10  -d=15  -e=43  -f=91 -g=187 -h=107 -i=17
fi

perl6 aff.p6 > etape-finale.html
exit

=begin POD

=encoding utf8

=head1 NOM

maj1 -- programme récapitulant le processus itératif de construction de la cartographie

=head1 DESCRIPTION

Ce programme réunit tous les appels de F<maj.p6> lors de la construction de la cartographie
de l'As des As. Cela permet de repartir à zéro et de tout refaire sans trop se fatiguer.

=head1 LANCEMENT

  sh maj1

=head2 Paramètres

Aucun paramètre

=head1 COPYRIGHT et LICENCE

Copyright 2018, Jean Forget

Ce programme est diffusé avec les mêmes conditions que Perl 5.16.3 :
la licence publique GPL version 1 ou ultérieure, ou bien la
licence artistique Perl.

Vous pouvez trouver le texte en anglais de ces licences dans le
fichier <LICENSE> joint ou bien aux adresses
L<http://www.perlfoundation.org/artistic_license_1_0>
et L<http://www.gnu.org/licenses/gpl-1.0.html>.

Résumé en anglais de la GPL :

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 1, or (at your option)
any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software Foundation,
Inc., L<http://www.fsf.org/>.

=end POD
