#!/bin/sh
# -*- encoding: utf-8; indent-tabs-mode: nil -*-
#
#
#     Programme affichant la cartographie partielle de l'As des As en HTML
#     Program displaying the partial map of Ace of Aces as an HTML file
#     Copyright (C) 2018 Jean Forget
#
#     Voir la licence dans la documentation incluse ci-dessous.
#     See the license in the embedded documentation below.
#

if [ 1 -ne 1 ]
then
  perl6 init.p6
  perl6 aff.p6 > etape0.html
  perl6 maj.p6 --page=187 -a=205 -b=187 -c=198 -d=3   -e=15  -f=16  -g=2   -h=17  -i=1
  perl6 aff.p6 > etape1.html
  perl6 maj.p6 --page=16  -a=24  -b=16  -c=10  -d=15  -e=43  -f=91  -g=187 -h=107 -i=17
  perl6 maj.p6 --page=91  -a=93  -b=91  -c=42  -d=43  -e=118 -f=119 -g=16  -h=120 -i=107
  perl6 maj.p6 --page=42  -a=91  -b=42  -c=52  -d=124 -e=125 -f=126 -g=53  -h=102 -i=10
  perl6 maj.p6 --page=52  -a=42  -b=52  -c=62  -d=131 -e=132 -f=41  -g=130 -h=27  -i=63
  perl6 maj.p6 --page=62  -a=52  -b=62  -c=83  -d=135 -e=51  -f=20  -g=134 -h=72  -i=133
  perl6 maj.p6 --page=83  -a=62  -b=83  -c=93  -d=61  -e=18  -f=94  -g=141 -h=139 -i=140
  perl6 maj.p6 --page=93  -a=83  -b=93  -c=91  -d=24  -e=92  -f=145 -g=82  -h=146 -i=147
  perl6 maj.p6 --page=198 -a=187 -b=198 -c=209 -d=35  -e=10  -f=11  -g=36  -h=12  -i=31
  perl6 maj.p6 --page=11  -a=17  -b=11  -c=34  -d=10  -e=102 -f=103 -g=198 -h=80  -i=12
  perl6 maj.p6 --page=103 -a=81  -b=103 -c=100 -d=102 -e=157 -f=158 -g=11  -h=159 -i=80
  perl6 maj.p6 --page=100 -a=103 -b=100 -c=40  -d=163 -e=164 -f=165 -g=41  -h=90  -i=34
  perl6 maj.p6 --page=40  -a=100 -b=40  -c=50  -d=167 -e=168 -f=101 -g=166 -h=21  -i=51
  perl6 maj.p6 --page=50  -a=40  -b=50  -c=71  -d=129 -e=39  -f=13  -g=128 -h=61  -i=127
  perl6 maj.p6 --page=71  -a=50  -b=71  -c=81  -d=49  -e=7   -f=82  -g=174 -h=172 -i=173
  perl6 maj.p6 --page=81  -a=71  -b=81  -c=103 -d=17  -e=107 -f=151 -g=70  -h=152 -i=153
fi

perl6 maj.p6 --page=209 -a=198 -b=209 -c=188 -d=27 -e=34 -f=33 -g=26 -h=32 -i=25
perl6 maj.p6 --page=33 -a=12 -b=33 -c=4 -d=34 -e=90 -f=79 -g=209 -h=68 -i=32
perl6 maj.p6 --page=79 -a=69 -b=79 -c=89 -d=90 -e=192 -f=193 -g=33 -h=194 -i=68
perl6 aff.p6 > etape-finale.html
exit

=begin POD

=encoding utf8

=head1 NOM

maj1 -- programme récapitulant le processus itératif de construction de la cartographie

=head1 DESCRIPTION

Ce programme réunit tous les appels de F<maj.p6> lors de la construction de la cartographie
de l'As des As. Cela permet de repartir à zéro et de tout refaire sans trop se fatiguer.

=head1 LANCEMENT

  sh maj1

=head2 Paramètres

Aucun paramètre

=head1 COPYRIGHT et LICENCE

Copyright 2018, Jean Forget

Ce programme est diffusé avec les mêmes conditions que Perl 5.16.3 :
la licence publique GPL version 1 ou ultérieure, ou bien la
licence artistique Perl.

Vous pouvez trouver le texte en anglais de ces licences dans le
fichier <LICENSE> joint ou bien aux adresses
L<http://www.perlfoundation.org/artistic_license_1_0>
et L<http://www.gnu.org/licenses/gpl-1.0.html>.

Résumé en anglais de la GPL :

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 1, or (at your option)
any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software Foundation,
Inc., L<http://www.fsf.org/>.

=end POD
