#!/bin/sh
# -*- encoding: utf-8; indent-tabs-mode: nil -*-
#
#
#     Programme affichant la cartographie partielle de l'As des As en HTML
#     Program displaying the partial map of Ace of Aces as an HTML file
#     Copyright (C) 2018 Jean Forget
#
#     Voir la licence dans la documentation incluse ci-dessous.
#     See the license in the embedded documentation below.
#

if [ 1 -ne 1 ]
then
  perl6 init.p6
  perl6 aff.p6 > etape0.html
  perl6 maj.p6 --page=187 -a=205 -b=187 -c=198 -d=3   -e=15  -f=16  -g=2   -h=17  -i=1
  perl6 aff.p6 > etape1.html
  perl6 maj.p6 --page=16  -a=24  -b=16  -c=10  -d=15  -e=43  -f=91  -g=187 -h=107 -i=17
  perl6 maj.p6 --page=91  -a=93  -b=91  -c=42  -d=43  -e=118 -f=119 -g=16  -h=120 -i=107
  perl6 maj.p6 --page=42  -a=91  -b=42  -c=52  -d=124 -e=125 -f=126 -g=53  -h=102 -i=10
  perl6 maj.p6 --page=52  -a=42  -b=52  -c=62  -d=131 -e=132 -f=41  -g=130 -h=27  -i=63
  perl6 maj.p6 --page=62  -a=52  -b=62  -c=83  -d=135 -e=51  -f=20  -g=134 -h=72  -i=133
  perl6 maj.p6 --page=83  -a=62  -b=83  -c=93  -d=61  -e=18  -f=94  -g=141 -h=139 -i=140
  perl6 maj.p6 --page=93  -a=83  -b=93  -c=91  -d=24  -e=92  -f=145 -g=82  -h=146 -i=147
  perl6 maj.p6 --page=198 -a=187 -b=198 -c=209 -d=35  -e=10  -f=11  -g=36  -h=12  -i=31
  perl6 maj.p6 --page=11  -a=17  -b=11  -c=34  -d=10  -e=102 -f=103 -g=198 -h=80  -i=12
  perl6 maj.p6 --page=103 -a=81  -b=103 -c=100 -d=102 -e=157 -f=158 -g=11  -h=159 -i=80
  perl6 maj.p6 --page=100 -a=103 -b=100 -c=40  -d=163 -e=164 -f=165 -g=41  -h=90  -i=34
  perl6 maj.p6 --page=40  -a=100 -b=40  -c=50  -d=167 -e=168 -f=101 -g=166 -h=21  -i=51
  perl6 maj.p6 --page=50  -a=40  -b=50  -c=71  -d=129 -e=39  -f=13  -g=128 -h=61  -i=127
  perl6 maj.p6 --page=71  -a=50  -b=71  -c=81  -d=49  -e=7   -f=82  -g=174 -h=172 -i=173
  perl6 maj.p6 --page=81  -a=71  -b=81  -c=103 -d=17  -e=107 -f=151 -g=70  -h=152 -i=153
  perl6 maj.p6 --page=209 -a=198 -b=209 -c=188 -d=27  -e=34  -f=33  -g=26  -h=32  -i=25
  perl6 maj.p6 --page=33  -a=12  -b=33  -c=4   -d=34  -e=90  -f=79  -g=209 -h=68  -i=32
  perl6 maj.p6 --page=79  -a=69  -b=79  -c=89  -d=90  -e=192 -f=193 -g=33  -h=194 -i=68
  perl6 maj.p6 --page=89  -a=79  -b=89  -c=98  -d=195 -e=196 -f=197 -g=101 -h=78  -i=4
  perl6 maj.p6 --page=98  -a=89  -b=98  -c=38  -d=161 -e=162 -f=99  -g=160 -h=14  -i=39
  perl6 maj.p6 --page=38  -a=98  -b=38  -c=60  -d=123 -e=97  -f=8   -g=122 -h=49  -i=121
  perl6 maj.p6 --page=60  -a=38  -b=60  -c=69  -d=37  -e=1   -f=70  -g=180 -h=178 -i=179
  perl6 maj.p6 --page=69  -a=60  -b=69  -c=79  -d=12  -e=80  -f=184 -g=59  -h=185 -i=186
  perl6 maj.p6 --page=188 -a=209 -b=188 -c=213 -d=21  -e=4   -f=5   -g=20  -h=6   -i=19
  perl6 maj.p6 --page=5   -a=32  -b=5   -c=28  -d=4   -e=78  -f=67  -g=188 -h=57  -i=6
  perl6 maj.p6 --page=67  -a=58  -b=67  -c=77  -d=78  -e=214 -f=215 -g=5   -h=216 -i=57
  perl6 maj.p6 --page=77  -a=67  -b=77  -c=87  -d=189 -e=190 -f=191 -g=99  -h=66  -i=28
  perl6 maj.p6 --page=87  -a=77  -b=87  -c=96  -d=155 -e=156 -f=88  -g=154 -h=9   -i=97
  perl6 maj.p6 --page=96  -a=87  -b=96  -c=48  -d=117 -e=86  -f=2   -g=116 -h=37  -i=115
  perl6 maj.p6 --page=48  -a=96  -b=48  -c=58  -d=95  -e=31  -f=59  -g=204 -h=202 -i=203
  perl6 maj.p6 --page=58  -a=48  -b=58  -c=67  -d=32  -e=68  -f=210 -g=47  -h=211 -i=212
  perl6 maj.p6 --page=213 -a=188 -b=213 -c=205 -d=14  -e=28  -f=29  -g=13  -h=30  -i=18
  perl6 maj.p6 --page=29  -a=6   -b=29  -c=22  -d=28  -e=66  -f=56  -g=213 -h=45  -i=30
  perl6 maj.p6 --page=56  -a=46  -b=56  -c=65  -d=66  -e=206 -f=207 -g=29  -h=208 -i=45
  perl6 maj.p6 --page=65  -a=56  -b=65  -c=75  -d=181 -e=182 -f=183 -g=88  -h=55  -i=22
  perl6 maj.p6 --page=75  -a=65  -b=75  -c=85  -d=149 -e=150 -f=76  -g=148 -h=3   -i=86
  perl6 maj.p6 --page=85  -a=75  -b=85  -c=108 -d=144 -e=74  -f=36  -g=143 -h=95  -i=142
  perl6 maj.p6 --page=108 -a=85  -b=108 -c=46  -d=84  -e=25  -f=47  -g=222 -h=220 -i=221
  perl6 maj.p6 --page=46  -a=108 -b=46  -c=56  -d=6   -e=57  -f=109 -g=105 -h=110 -i=111
  perl6 maj.p6 --page=205 -a=213 -b=205 -c=187 -d=9   -e=22  -f=23  -g=8   -h=24  -i=7
  perl6 maj.p6 --page=23  -a=30  -b=23  -c=15  -d=22  -e=55  -f=44  -g=205 -h=92  -i=24
  perl6 maj.p6 --page=44  -a=104 -b=44  -c=54  -d=55  -e=199 -f=200 -g=23  -h=201 -i=92
fi

perl6 maj.p6 --page=54  -a=44  -b=54  -c=64  -d=175 -e=176 -f=177 -g=76  -h=43  -i=15
perl6 maj.p6 --page=64  -a=54  -b=64  -c=73  -d=170 -e=171 -f=53  -g=169 -h=35  -i=74
perl6 maj.p6 --page=73  -a=64  -b=73  -c=106 -d=138 -e=63  -f=26  -g=137 -h=84  -i=136
perl6 maj.p6 --page=106 -a=73  -b=106 -c=104 -d=72  -e=19  -f=105 -g=114 -h=112 -i=113
perl6 maj.p6 --page=104 -a=106 -b=104 -c=44  -d=30  -e=45  -f=217 -g=94  -h=218 -i=219
perl6 aff.p6 > etape-finale.html
exit

=begin POD

=encoding utf8

=head1 NOM

maj1 -- programme récapitulant le processus itératif de construction de la cartographie

=head1 DESCRIPTION

Ce programme réunit tous les appels de F<maj.p6> lors de la construction de la cartographie
de l'As des As. Cela permet de repartir à zéro et de tout refaire sans trop se fatiguer.

=head1 LANCEMENT

  sh maj1

=head2 Paramètres

Aucun paramètre

=head1 COPYRIGHT et LICENCE

Copyright 2018, Jean Forget

Ce programme est diffusé avec les mêmes conditions que Perl 5.16.3 :
la licence publique GPL version 1 ou ultérieure, ou bien la
licence artistique Perl.

Vous pouvez trouver le texte en anglais de ces licences dans le
fichier <LICENSE> joint ou bien aux adresses
L<http://www.perlfoundation.org/artistic_license_1_0>
et L<http://www.gnu.org/licenses/gpl-1.0.html>.

Résumé en anglais de la GPL :

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 1, or (at your option)
any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software Foundation,
Inc., L<http://www.fsf.org/>.

=end POD
